default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_o1_v02_extendedEndcap/jets/ 
        fileName:
                - OVERLAY/jetStudy_PandoraPFOs.root
                - noOverlay/jetStudy.root
        legTitle:
                - "with Overlay"
                - "w/o Overlay"
        legPos:
                - 0.2
                - 0.2
                - 0.4
                - 0.4
        scaleFactor: 0.1
        rebinFactor: 10
        xAxisRange:
                - -0.2
                - 1
        markerStyle:
                - 0
                - 0


hist_nPFOsVsCosTheta_all:
        histName:
                - jetStudy/nPFOsVsCosTheta/all 
        yAxisLabel: "nPFOs per event"
hist_nPFOsVsCosTheta_electron:
        histName:
                - jetStudy/nPFOsVsCosTheta/Electron 
        yAxisLabel: "nElectrons per event"
hist_nPFOsVsCosTheta_muon:
        histName:
                - jetStudy/nPFOsVsCosTheta/Muon 
        yAxisLabel: "nMuons per event"
hist_nPFOsVsCosTheta_photon:
        histName:
                - jetStudy/nPFOsVsCosTheta/Photon 
        yAxisLabel: "nPhotons per event"
hist_nPFOsVsCosTheta_pion:
        histName:
                - jetStudy/nPFOsVsCosTheta/Pion 
        yAxisLabel: "nPions per event"
hist_nPFOsVsCosTheta_NeutralHadron:
        histName:
                - jetStudy/nPFOsVsCosTheta/NeutralHadron 
        yAxisLabel: "nNeutralHadrons per event"
hist_nPFOs:
        histName:
                - jetStudy/nPFOs
        scaleFactor: 0.5
        rebinFactor: 2
        xAxisRange:
                - 0
                - 100
hist_totalEnergyVsCosTheta:
        histName:
                - jetStudy/totalEnergyVsCosTheta
        xAxisLabel: "cos(#theta)"

