default:
        legTitle:
                - "Conformal Tracking"
                - "Truth Tracking"
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/ 
        markerStyle:
                - 0
                - 0
                - 0
        histName:
                - ResVsCosTheta
        legPos:
                - 0.2
                - 0.75
                - 0.85
                - 0.9



JER_truth_vs_conformal_Zuds91:
        fileName:
                - FCCee_extendedEcalEndcap/hist_Zuds91.root
                - FCCee_conformalTracking/hist_Zuds91.root
        yAxisRange:
                - 0
                - 20

JER_truth_vs_conformal_Zuds380:
        fileName:
                - nominal_trackClusterDistance/hist_Zuds380.root
                - FCCee_conformalTracking/hist_Zuds380.root
        yAxisRange:
                - 0
                - 20
