default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/ 
        legTitle:
                # - "no Brem"
                - "CLD"
        histName: 
                - Graph 
        legPos:
                - 0.5
                - 0.2
                - 0.9
                - 0.35
        xAxisRange:
                - 0
                - 120
        yAxisRange:
                - 0.8
                - 1.0
        drawOption: ALP
        sameDrawOption: LP
        xAxisLabel: "Energy [GeV]"
        yAxisLabel: "Efficiency"
        histColor:
                - 2

CLD_electron_eff:
        fileName:
                # - FCCee_o1_v02/electrons/50mm_trackClusterDistanceCut/noConv/eventHists_noFSR.root
                # - FCCee_o1_v02/electrons/50mm_trackClusterDistanceCut/fullSample/eventHists.root
                # - FCCee_o1_v02/electrons/nominal_withCaloInfo/eventHists.root
                - FCCee_o1_v02_extendedEndcap/electron/conformal_iLCSoft_2017_12_21/eventHists_photonAndNeutralRecl_looseThetaCut.root
