default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/ 
        legTitle:
                # - "conformal"
                # - "truth"
                - CLD
        histName: 
                - Graph 
        legPos:
                - 0.2
                - 0.2
                - 0.9
                - 0.35
        xAxisRange:
                - 0
                - 120
        yAxisRange:
                - 0.8
                - 1.0
        drawOption: ALP
        sameDrawOption: LP
        xAxisLabel: "Energy [GeV]"
        yAxisLabel: "Efficiency"
        # histColor:
        #         - 2

CLD_pions_eff_truth_vs_conformal:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_o1_v02_extendedEndcap/pion/conformal_iLCSoft_2017_12_21/
        fileName:
                - eventHists.root
                - eventHists_photonRecl_noAngularMatching.root
                - eventHists_photonRecl_noEnergyMatching.root
        legTitle:
                - "regular eff. criteria"
                - "type and energy matching only"
                - "type and angular matching only"

# CLD_muons_eff_truth_vs_conformal:
#         fileName:
#                 - FCCee_o1_v02_extendedEndcap/muon/conformal_iLCSoft_2017_12_21/eventHists.root
#                 # - FCCee_o1_v02/muons/eventHists.root
#         yAxisRange:
#                 - 0.6
#                 - 1.0
