# calice_photonEff_vs_energy_reclustering_CLIC:
calice_photonEff_vs_energy_reclustering_FCCee:
        # dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/CLIC_o3_v14/photons/
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_o1_v02/photons/
        legTitle:
                # - "nominal efficiency"
                # - "photon cluster merging"
                # - "photon+neutral cluster merging"
                - "CLD"
                # - "no convertion"
        fileName:
                # - eventHists.root
                # - eventHists_photonRecl.root
                - eventHists_photonAndNeutralRecl_looseThetaCut.root
                # - eventHists_noConv.root
        histName: 
                - Graph 
        legPos:
                - 0.5
                - 0.2
                - 0.9
                - 0.35
        xAxisRange:
                - 0
                - 120
        yAxisRange:
                - 0.6
                - 1.0
        drawOption: ALP
        sameDrawOption: LP
        xAxisLabel: "Energy [GeV]"
        yAxisLabel: "Efficiency"
        histColor:
                - 2


