CLIC_eff_vs_theta_3:
        # dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/gamma/FCCee_testConvertionDetection/fullTheta2/
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/CLIC_singleParticle_performace/gammaIsoGun/ 
        fileName:
                - particleGun_E100.root
        legTitle:
                - "all photons"
                - "unconverted photons"
                - "converted photons"
                - "photon merging"
        histName: 
                - eventHists/efficiencyVsCosTheta
                - eventHists_noConv/efficiencyVsCosTheta
                - eventHists_conv/efficiencyVsCosTheta
                - eventHists_photonRecl/efficiencyVsCosTheta
                # - eventHists_photonAndNeutralRecl/efficiencyVsCosTheta
        legPos:
                - 0.3
                - 0.45
                - 0.7
                - 0.58
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        # xAxisRange:
        #         - 0
        #         - 120
        yAxisRange:
                - 0.2
                - 1.1
        histTitle: "photon identification efficiency, E=100 GeV"
        # legCaptionMode: entries
        # logY: 1
        rebinFactor: 4
        scaleFactor: 0.25
        drawOptions: H
        yAxisLabel: Efficiency
        xAxisLabel: "cos(#theta_{true})"
