default:
        # dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_o1_v02_extendedEndcap/pion/conformal_iLCSoft_2017_12_21/ 
        legTitle:
                - "no charged PFOs"
                - "1 electron PFO"
                - "1 pion PFO"
                - "other"
                - "sum (validation)"
        histName:
                - eventHists/efficiencyVsCosThetaCat1
                - eventHists/efficiencyVsCosThetaCat2
                - eventHists/efficiencyVsCosThetaCat3
                - eventHists/efficiencyVsCosThetaCat4
                - eventHists/efficiencyVsCosThetaCat0
                # - eventHists/efficiencyVsCosTheta
        legPos:
                - 0.3
                - 0.3
                - 0.8
                - 0.5
        yAxisRange:
                - 0.0
                - 1.1
        drawOption: HIST
        yAxisLabel: Efficiency
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0
        rebinFactor: 4
        scaleFactor: 0.25


calice_FCCee_effVsTheta_fakes_pions_E100:
        fileName:
                - particleGun_E100_Theta9_171.root

