default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/ 
        legTitle:
                - "no charged PFOs"
                - "1 electron PFO"
                - "1 pion PFO"
                - "other"
                - "sum (validation)"
        histName:
                - eventHists/efficiencyVsCosThetaCat1
                - eventHists/efficiencyVsCosThetaCat2
                - eventHists/efficiencyVsCosThetaCat3
                - eventHists/efficiencyVsCosThetaCat4
                - eventHists/efficiencyVsCosThetaCat0
                # - eventHists/efficiencyVsCosTheta
        legPos:
                - 0.3
                - 0.3
                - 0.8
                - 0.5
        yAxisRange:
                - 0.0
                - 1.1
        drawOption: HIST
        yAxisLabel: Efficiency
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0
        rebinFactor: 4
        scaleFactor: 0.25

#
# calice_CLIC_vs_FCCee_effVsTheta_fakes_electrons_E5:
#         fileName:
#                 - FCCee_o1_v02/electrons/particleGun_E5_Theta9_171.root
#
# calice_CLIC_vs_FCCee_effVsTheta_fakes_electrons_E100:
#         fileName:
#                 - FCCee_o1_v02/electrons/particleGun_E100_Theta9_171.root
#
# calice_CLIC_vs_FCCee_effVsTheta_fakes_electrons_E50:
#         fileName:
#                 - FCCee_o1_v02/electrons/particleGun_E50_Theta9_171.root
#
# calice_CLIC_vs_FCCee_effVsTheta_fakes_electrons_E20:
#         fileName:
#                 - FCCee_o1_v02/electrons/particleGun_E20_Theta9_171.root
#
calice_CLIC_vs_FCCee_effVsTheta_fakes_electrons_E10:
        fileName:
                - FCCee_o1_v02/electrons/particleGun_E10_Theta9_171.root
                # - CLIC_o3_v14/electrons/particleGun_E10_Theta9_171.root







# calice_CLIC_vs_FCCee_effVsTheta_fakes_electrons_E2:
#         fileName:
#                 - CLIC_o3_v14/electrons/particleGun_E2_Theta9_171.root
                # - FCCee_o1_v02/electrons/particleGun_E2_Theta9_171.root

# calice_CLIC_vs_FCCee_effVsTheta_fakes_electrons_E1:
#         fileName:
#                 - CLIC_o3_v14/electrons/particleGun_E1_Theta9_171.root
#                 - FCCee_o1_v02/electrons/particleGun_E1_Theta9_171.root


