ecal_to_hcal_ratio_photonPFO:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/build/PhotonECAL/FCCee_singleParticle_performace/kaon0L/nominalEfficiency/test/
        fileName:
                - particleGun_E50_Theta47_Phi0.root
                - particleGun_E50_Theta38_Phi0.root
        legTitle:
                - Theta 46 - 48
                - Theta 33 - 43
        histName: 
                - PandoraPFOs_22/signalPFO_noAdditionalPFOs_clusterInfo/ECALtoHCALRatio
        legPos:
                - 0.5
                - 0.7
                - 0.9
                - 0.9
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        xAxisRange:
                - 0
                - 20
        # yAxisRange:
        #         - 0
        #         - 5000
        # histTitle: "K^{0}_{L} gun, E: 50 GeV"
        histTitle: "Photon PFOs vs. ECAL to HCAL energy ratio"
        # legCaptionMode: mean
        rebinFactor: 2
