default:
        drawOption: ALP
        sameDrawOption: LP
        sortXaxisInGraph: True
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_o1_v03/kaons/
        histName: 
                - Graph
        lineWidth: 0
        # histColor:
        #         - 1
        #         - 2
        #         - 8
        #         - 12
        canPos:
                - 0
                - 0
                - 800
                - 800
        yAxisLabel: "#sigma(E_{K^{0}_{L}})/E_{K^{0}_{L}} [%]"
        yAxisTitleOffset: 0.98
        xAxisLabel: Energy [GeV]
        yAxisRange:
                - 4.5 
                - 25.0
        markerSize: 1.6
        textLabel0:
            pos:
                - 0.0
                - 1.02
            title: "FCC-ee CLD"
            TextSize: 0.04

jun28_kaonRes_vs_energy:
        gridX: 1
        gridY: 1
        fileName:
                - theta60_120/eventHists_NeutralHadron.root
                - theta45_60/eventHists_NeutralHadron.root
                - theta15_45/eventHists_NeutralHadron.root
                # - theta15_35/eventHists_NeutralHadron.root
        legTitle:
                - "barrel (#theta: 60#circ-120#circ)"
                - "transition (#theta: 45#circ-60#circ)"
                - "endcap (#theta: 15#circ-45#circ)"
        legPos:
                - 0.3
                - 0.7
                - 0.85
                - 0.9

