default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/TEMPLATES/
        legPos:
                - 0.2
                - 0.7
                - 0.58
                - 0.9
        yAxisRange:
                - 2.5
                - 8
        yAxisTitleOffset: 0.95
        # skipMissingHists: 1
        histName: 
                - ResVsCosTheta


# JER_SWC_2-100_vs_2-200_91.2GeV:
#         legTitle:
#                 - "2-200 GeV"
#                 - "2-100 GeV"
#         fileName:
#                 - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds91.2_E365_ConformalTr_defaultSetting_jun26_files/hists.root
#                 - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds91.2_SWC2-100_E365_ConformalTr_defaultSetting_jun26_files/hists.root
#
# JER_SWC_2-100_vs_2-200_365GeV:
#         legTitle:
#                 - "2-200 GeV"
#                 - "2-100 GeV"
#         fileName:
#                 - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds365_E365_ConformalTr_defaultSetting_jun26_files/hists.root
#                 - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds365_SWC2-100_E365_ConformalTr_defaultSetting_jun26_files/hists.root


# JER_380_vs_365:
#         legTitle:
#                 - "380 GeV"
#                 - "365 GeV"
#         fileName:
#                 - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E380_ConformalTr_run1_files/hists.root
#                 - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds365_E365_ConformalTr_defaultSetting_jun26_files/hists.root
#
# JER_91_vs_91_2:
#         legTitle:
#                 - "91 GeV"
#                 - "91.2 GeV"
#         fileName:
#                 - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E91_ConformalTr_run1_files/hists.root
#                 - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds91.2_E365_ConformalTr_defaultSetting_jun26_files/hists.root

# JER_91_RMS90_vs_GaussSigma:
#         legTitle:
#                 - "RMS90: 45.5 GeV Jets"
#                 # - "Gauss 3*Sigma: 45.5 GeV Jets"
#                 - "Gauss 2*Sigma: 45.5 GeV Jets"
#                 # - "Gauss 5*Sigma: 45.5 GeV Jets"
#         fileName:
#                 - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E91_ConformalTr_run1_files/hists.root
#         histName:
#                 - ResVsCosTheta
#                 # - Gaus3SigmaResVsCosTheta
#                 - Gaus2SigmaResVsCosTheta
#                 # - Gaus5SigmaResVsCosTheta

JER_91_2_RMS90_vs_GaussSigma:
        legTitle:
                - "RMS90: 45.6 GeV Jets"
                # - "Gauss 3*Sigma: 45.5 GeV Jets"
                - "Gauss 2*Sigma: 45.6 GeV Jets"
                # - "Gauss 5*Sigma: 45.5 GeV Jets"
        fileName:
                - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds91.2_E365_ConformalTr_defaultSetting_jun26_files/hists.root
        histName: 
                - ResVsCosTheta
                # - Gaus3SigmaResVsCosTheta
                - Gaus2SigmaResVsCosTheta
                # - Gaus5SigmaResVsCosTheta
                  
JER_365_RMS90_vs_GaussSigma:
        legTitle:
                - "RMS90: 182.5 GeV Jets"
                # - "Gauss 3*Sigma: 182.5 GeV Jets"
                - "Gauss 2*Sigma: 182.5 GeV Jets"
                # - "Gauss 5*Sigma: 182.5 GeV Jets"
        fileName:
                - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds365_E365_ConformalTr_defaultSetting_jun26_files/hists.root
        histName: 
                - ResVsCosTheta
                # - Gaus3SigmaResVsCosTheta
                - Gaus2SigmaResVsCosTheta
                # - Gaus5SigmaResVsCosTheta

JER_91_2_RMS90_vs_GaussSigma_newRelease:
        legTitle:
                - "2018-08-10: RMS90: 45.6 GeV Jets"
                - "2018-08-10: Gauss 2*Sigma: 45.6 GeV Jets"
                # - "2018-05-18: RMS90: 45.6 GeV Jets"
                # - "2018-05-18: Gauss 2*Sigma: 45.6 GeV Jets"
        fileName:
                - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_ConformalTr_defaultSetting_jun26_files/hists.root
                # - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds91.2_E365_ConformalTr_defaultSetting_jun26_files/hists.root
        histName: 
                - ResVsCosTheta
                - Gaus2SigmaResVsCosTheta
        skipMissingHists: 1
                  
JER_365_RMS90_vs_GaussSigma_newRelease:
        legTitle:
                - "2018-08-10: RMS90: 182.5 GeV Jets"
                - "2018-08-10: Gauss 2*Sigma: 182.5 GeV Jets"
                # - "2018-05-18: RMS90: 182.5 GeV Jets"
                # - "2018-05-18: Gauss 2*Sigma: 182.5 GeV Jets"
        fileName:
                - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E365_ConformalTr_defaultSetting_jun26_files/hists.root
                # - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds365_E365_ConformalTr_defaultSetting_jun26_files/hists.root
        histName: 
                - ResVsCosTheta
                - Gaus2SigmaResVsCosTheta
        skipMissingHists: 1

# jun29_Zuds91_vs_Zuds365:
#         legTitle:
#                 - "45.5 GeV Jets"
#                 - "182.5 GeV Jets"
#         fileName:
#                 - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E91_ConformalTr_run1_files/hists.root
#                 # - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds91.2_E365_ConformalTr_defaultSetting_jun26_files/hists.root
#                 - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_zuds365_E365_ConformalTr_defaultSetting_jun26_files/hists.root

