default:
        drawOption: AP
        sameDrawOption: P
        # sortXaxisInGraph: True
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/TEMPLATES/
        # lineWidth: 0
        # canPos:
                # - 0
                # - 0
                # - 800
                # - 800
        # yAxisLabel: "#sigma(E_{K^{0}_{L}})/E_{K^{0}_{L}} [%]"
        yAxisTitleOffset: 0.96
        # xAxisLabel: Energy [GeV]
        yAxisRange:
                - 3.5
                - 5.0
        # markerSize: 1.6
        histColor:
                - 625 
                - 1
        textLabel0:
            pos:
                - 0.0
                - 1.02
            title: "FCC-ee CLD"
            TextSize: 0.04

JER_SWC_noWC_vs_energy_res7:
        histName: 
                - res7
        # gridX: 1
        # gridY: 1
        fileName:
                - noSWC/resVsEnergyGraphs.root
                - resVsEnergyGraphs.root
        legTitle:
                - "no energy correction"
                - "with software compensation"
        legPos:
                - 0.3
                - 0.7
                - 0.85
                - 0.9

