default:
    yAxisTitleOffset: 0.95
    textLabel1:
        pos:
        - 0.04 
        - 0.49 
        title: "VLC11 Jets"
    latexLabel1:
        pos:
        - 0.04
        - 0.28 
        title: "#approx 45.6 GeV"
    # savePictDir: "JER_fitting_91GeV_logy"
    # logY: True
    savePictDir: "JER_fitting_91GeV"
    logY: False
    legTitle:
        - ""
    yAxisRange:
        - 0.1
        - 1100 
    xAxisRange:
        - 0.5
        - 1.5
    dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/TEMPLATES/
    fileName:
        - FCCee_o1_v03_ILCSoft-2018-10-11_gcc62_zuds_E91.2_ConformalTr_400ns_Overlay_run1_files/DR11_165bins.root
    markerStyle:
        - 1
        - 1
    drawHistFuncs: False
    xAxisLabel: "E_{j}^{R}/E_{j}^{G}"
    yAxisLabel: "A.U."
    yAxisTitleSize: 0.055
    yAxisTitleOffset: 1.3
    xAxisTitleSize: 0.055
    xAxisTitleOffset: 1.2

JER_91GeV_fit_hist0:
    histName:
        - jetClustering/fPFA_0
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "489.540    1.009    0.038    1.302    4.265    1.000    5.944"
    latexLabel2:
        pos:
        - 0.57
        - 0.49 
        title: "0.0 < cos(#theta) < 0.1"

JER_91GeV_fit_hist1:
    histName:
        - jetClustering/fPFA_1
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "495.569    1.009    0.039    1.371    6.794    1.000    5.868"
    latexLabel2:
        pos:
        - 0.57
        - 0.49 
        title: "0.1 < cos(#theta) < 0.2"

JER_91GeV_fit_hist2:
    histName:
        - jetClustering/fPFA_2
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "527.466    1.010    0.038    1.290    5.023    1.000    5.866"
    latexLabel2:
        pos:
        - 0.57
        - 0.49 
        title: "0.2 < cos(#theta) < 0.3"

JER_91GeV_fit_hist3:
    histName:
        - jetClustering/fPFA_3
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "540.688    1.009    0.037    1.204    6.424    1.000    6.972"
    latexLabel2:
        pos:
        - 0.57
        - 0.49 
        title: "0.3 < cos(#theta) < 0.4"

JER_91GeV_fit_hist4:
    histName:
        - jetClustering/fPFA_4
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "605.294    1.012    0.037    1.136    7.597    1.000    7.330"
    latexLabel2:
        pos:
        - 0.57
        - 0.49 
        title: "0.4 < cos(#theta) < 0.5"

JER_91GeV_fit_hist5:
    histName:
        - jetClustering/fPFA_5
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "584.009    1.014    0.040    1.271    7.719    1.000    9.754"
    latexLabel2:
        pos:
        - 0.57
        - 0.49 
        title: "0.5 < cos(#theta) < 0.6"

JER_91GeV_fit_hist6:
    histName:
        - jetClustering/fPFA_6
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "563.319    1.018    0.045    1.332    6.000    1.000    9.509"
    latexLabel2:
        pos:
        - 0.57
        - 0.49 
        title: "0.6 < cos(#theta) < 0.7"

JER_91GeV_fit_hist7:
    histName:
        - jetClustering/fPFA_7
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "631.642    1.017    0.045    1.358    7.630    1.000    9.221"
    latexLabel2:
        pos:
        - 0.57
        - 0.49 
        title: "0.7 < cos(#theta) < 0.8"

JER_91GeV_fit_hist8:
    histName:
        - jetClustering/fPFA_8
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "616.213    1.017    0.046    1.176   28.563    1.000    6.137"
    latexLabel2:
        pos:
        - 0.57
        - 0.49 
        title: "0.8 < cos(#theta) < 0.9"

JER_91GeV_fit_hist9:
    histName:
        - jetClustering/fPFA_9
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "156.725    1.025    0.046    1.397    2.822    1.000    5.420"
    latexLabel2:
        pos:
        - 0.48
        - 0.49 
        title: "0.9 < cos(#theta) < 0.925"

JER_91GeV_fit_hist10:
    histName:
        - jetClustering/fPFA_10
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "128.836    1.031    0.055    1.316    6.254    1.000    9.320"
    latexLabel2:
        pos:
        - 0.48
        - 0.49 
        title: "0.925 < cos(#theta) < 0.95"

JER_91GeV_fit_hist11:
    histName:
        - jetClustering/fPFA_11
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "104.716    1.033    0.054    1.085    5.011    1.000    3.074"
    latexLabel2:
        pos:
        - 0.48
        - 0.49 
        title: "0.95 < cos(#theta) < 0.975"

JER_91GeV_fit_hist12:
    histName:
        - jetClustering/fPFA_12
    tf1: # /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/91GeV_400ns_st2/hist_0.txt
        func: "dscb"
        range:
            - 0.5
            - 1.5
        parameters: "55.925    1.017    0.071    1.137    2.419    1.045    3.320"
    latexLabel2:
        pos:
        - 0.48
        - 0.49 
        title: "0.975 < cos(#theta) < 1.0"

