CLIC_dPhi_1:
        # dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/gamma/FCCee_testConvertionDetection/fullTheta2/
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/CLIC_singleParticle_performace/gammaIsoGun/ 
        fileName:
                - particleGun_E100.root
        legTitle:
                # - "all photons"
                - "unconverted photons"
                - "converted photons"
                # - "photon merging"
        histName: 
                # - eventHists/efficiencyVsCosTheta
                - eventHists_noConv/phiResolution_photon
                - eventHists_conv/phiResolution_photon
                # - eventHists_photonRecl/efficiencyVsCosTheta
                # - eventHists_photonAndNeutralRecl/efficiencyVsCosTheta
        legPos:
                - 0.12
                - 0.75
                - 0.48
                - 0.88
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        # xAxisRange:
        #         - 0
        #         - 120
        yAxisRange:
                - 0.0
                - 2000
        histTitle: "photon angular resolution , E=100 GeV"
        # legCaptionMode: entries
        # logY: 1
        rebinFactor: 1
        # scaleFactor: 0.25
        drawOptions: H
        yAxisLabel: Counts
        xAxisLabel: "#phi_{true} - #phi_{reco} [rad]"
