default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/
        legTitle:
                - "efficiency (pions, E=100 GeV)"
                - "fail type"
                - "fail angular matching"
                - "fail energy mathing"
                - "sum (validation)"
        histName:
                - eventHists/efficiencyVsCosTheta
                - eventHists/efficiencyVsCosThetaFailType/all
                - eventHists/efficiencyVsCosThetaFailAngularMatching
                - eventHists/efficiencyVsCosThetaFailEnergyMatching
                - eventHists/efficiencyVsCosThetaSum
        legPos:
                - 0.3
                - 0.3
                - 0.8
                - 0.5
        yAxisRange:
                - 0.0
                - 1.3
        rebinFactor: 4
        scaleFactor: 0.25
        drawOption: HIST
        yAxisLabel: Efficiency
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0

calice_ineff_pions_CLIC_E100:
        fileName:
                - CLIC_o3_v14/pions/particleGun_E100_Theta9_171.root 
                # - FCCee_o1_v02/pions/particleGun_E100_Theta9_171.root

calice_ineff_pions_FCCee_E100:
        fileName:
                # - CLIC_o3_v14/pions/particleGun_E100_Theta9_171.root
                - FCCee_o1_v02/pions/particleGun_E100_Theta9_171.root
