scale_vs_energy:
        drawOption: ALP
        sameDrawOption: LP
        sortXaxisInGraph: True
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/build/PhotonECAL/FCCee_singleParticle_performace/gamma/nominalEfficiency_nov1/out/
        # dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/build/PhotonECAL/FCCee_singleParticle_performace/kaon0L/nominalEfficiency_nov1/out/
        fileName:
                - outFile.root
        # legTitle:
        #         - one cluster per event
        histName: 
                - energy_energyResolution
        # legPos:
        #         - 0.4
        #         - 0.2
        #         - 0.85
        #         - 0.4
        lineWidth: 0
        histColor:
                - 1
                - 2
                - 8
                - 12
        canPos:
                - 0
                - 0
                - 800
                - 800

        yAxisLabel: "#sigma(E_{PFO})/E_{PFO} [%]"
        xAxisLabel: Energy [GeV]
        gridX: 1
        gridY: 1
        yAxisRange:
                - 0.0
                - 8.0
        markerSize: 1.6
