eff_vs_theta:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/build/PhotonECAL/FCCee_singleParticle_performace/pi-/iLCSoft_2017_10_20/ 
        fileName:
                - particleGun_E10_Theta0_Phi0_iLCSoft_2017_10_20.root
                - particleGun_E10_Theta0_Phi0.root
        legTitle:
                - iLCSoft_2017_10_20
                - iLCSoft_2017_07_27
        histName: 
                - photonEfficiency/efficiency_vs_cosTheta 
        legPos:
                - 0.25
                - 0.2
                - 0.65
                - 0.4
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        # xAxisRange:
        #         - 40
        #         - 50
        yAxisRange:
                - 0.8
                - 1.05
        yAxisLabel: Efficiency
        histTitle: "10 GeV Pions"
        # drawOption: "E1"
        # sameDrawOption: "E1"
