scale_vs_energy:
        drawOption: ALP
        sameDrawOption: LP
        sortXaxisInGraph: True
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/build/PhotonECAL/FCCee_singleParticle_performace/gamma/
        fileName:
                - test_efficiency_oneClusterRequirement/out/outFile.root
                - test_efficiency_noOneClusterRequirement/out/outFile.root
        legTitle:
                - one cluster per event
                - any number of cluster
        histName: 
                - energy_energyScaleBias
        legPos:
                - 0.4
                - 0.2
                - 0.85
                - 0.4
        histColor:
                - 1
                - 2
                - 8
                - 12
        yAxisLabel: Scale Bias [%]
        xAxisLabel: Energy [GeV]
        yAxisRange:
                - -1.5
                - 1.6
