eff_vs_energy:
        drawOption: ALP
        sameDrawOption: LP
        sortXaxisInGraph: True
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/build/PhotonECAL/FCCee_singleParticle_performace/e-/
        fileName:
                - out/outFile.root
                - test2/out/outFile.root
                - merge_dPhi2/out/outFile.root
        legTitle:
                - nominal efficiency
                - no bremsstrahlung
                - merge neutral clusters within |dPhi|<2^{o}
        histName: 
                - energy_efficiency
        legPos:
                - 0.4
                - 0.2
                - 0.85
                - 0.4
        histColor:
                - 1
                - 2
                - 8
                - 12
        yAxisLabel: Efficiency
        xAxisLabel: Energy [GeV]
        yAxisRange:
                - 0.75
                - 1.0
