eff_vs_energy_theta60_120:
        drawOption: ALP
        sameDrawOption: LP
        sortXaxisInGraph: True
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/python/theta60_120/ 
        fileName:
                - eventHists.root
                - eventHists_noConv.root
                # - eventHists_photonRecl.root
                - eventHists_photonAndNeutralRecl.root
                - eventHists_photonAndNeutralRecl2.root
        legTitle:
                - default efficiency
                - no convertion events
                # - photon reclustering
                - photon+neutral reclustering
                - photon+neutral reclustering (looser angle cut)
        histName: 
                - Graph 
        legPos:
                - 0.4
                - 0.2
                - 0.85
                - 0.4
        lineWidth: 1
        histColor:
                - 1
                - 2
                - 8
                - 12
        canPos:
                - 0
                - 0
                - 800
                - 800
        yAxisLabel: "Efficiency"
        xAxisLabel: "Energy [GeV]"
        gridX: 1
        gridY: 1
        yAxisRange:
                - 0.8
                - 1.0
        markerSize: 1.2
        drawOption: ACP
        sameDrawOption: CP
eff_vs_energy_looserAngle:
        drawOption: ALP
        sameDrawOption: LP
        sortXaxisInGraph: True
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/python/theta8_172_looserAngleCut/ 
        fileName:
                - eventHists.root
                - eventHists_noConv.root
                - eventHists_photonRecl.root
                - eventHists_photonAndNeutralRecl.root
        legTitle:
                - default efficiency
                - no convertion events
                - photon reclustering
                - photon+neutral reclustering
        histName: 
                - Graph 
        legPos:
                - 0.4
                - 0.2
                - 0.85
                - 0.4
        lineWidth: 1
        histColor:
                - 1
                - 2
                - 8
                - 12
        canPos:
                - 0
                - 0
                - 800
                - 800
        yAxisLabel: "Efficiency"
        xAxisLabel: "Energy [GeV]"
        gridX: 1
        gridY: 1
        yAxisRange:
                - 0.8
                - 1.0
        markerSize: 1.2
        drawOption: ACP
        sameDrawOption: CP
eff_vs_energy:
        drawOption: ALP
        sameDrawOption: LP
        sortXaxisInGraph: True
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/python/theta8_172/ 
        fileName:
                - eventHists.root
                - eventHists_noConv.root
                - eventHists_photonRecl.root
                - eventHists_photonAndNeutralRecl.root
        legTitle:
                - default efficiency
                - no convertion events
                - photon reclustering
                - photon+neutral reclustering
        histName: 
                - Graph 
        legPos:
                - 0.4
                - 0.2
                - 0.85
                - 0.4
        lineWidth: 1
        histColor:
                - 1
                - 2
                - 8
                - 12
        canPos:
                - 0
                - 0
                - 800
                - 800
        yAxisLabel: "Efficiency"
        xAxisLabel: "Energy [GeV]"
        gridX: 1
        gridY: 1
        yAxisRange:
                - 0.8
                - 1.0
        markerSize: 1.2
        drawOption: ACP
        sameDrawOption: CP
