default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_o1_v02/electrons/
        fileName:
                - 50mm_trackClusterDistanceCut/particleGun_E10_Theta9_171.root
                - 20mm_trackClusterDistanceCut/particleGun_E10_Theta9_171.root
                - nominal_withCaloInfo/particleGun_E10_Theta9_171.root
        legTitle:
                - "Mod cut (50mm, 50mm)"
                - "Mod cut (20mm, 20mm)"
                - "Nominal cut (3mm, 10mm)"
        legPos:
                - 0.3
                - 0.6
                - 0.68
                - 0.8
        yAxisRange:
                - 0
                - 0.4
        drawOption: HIST
        markerStyle:
                - 0
                - 0
                - 0
        rebinFactor: 10
        scaleFactor: 0.1

TrackClusterDistanceCut_failTypeInefficiency_all:
        histName: 
                - eventHists/efficiencyVsCosThetaFailType/all
        yAxisLabel: "Inefficiency (no electron) [%]"

TrackClusterDistanceCut_failTypeInefficiency_pion:
        histName: 
                - eventHists/efficiencyVsCosThetaFailType/pion
        yAxisLabel: "Inefficiency (no electron && pion) [%]"

TrackClusterDistanceCut_failTypeInefficiency_noChargedParts:
        histName: 
                - eventHists/efficiencyVsCosThetaFailType/noChargedParts
        yAxisLabel: "Inefficiency (no charged particles) [%]"
        
