electronTrackClusterPlot1:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/e-_testing/e-/ 
        fileName:
                - particleGun_E10_Theta9_171.root 
        legTitle:
                - "Electron"
        histName: 
                - electronStudy/OneElectronOnePhoton/trackClusterParallelDistance-Electron1
        legPos:
                - 0.3
                - 0.6
                - 0.68
                - 0.8
        histColor:
                - 1
        xAxisRange:
                - 0
                - 105
        drawOption: HIST
        xAxisLabel: "Parallel Distance [mm]"
        markerStyle:
                - 0

electronTrackClusterPlot2:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/e-_testing/e-/ 
        fileName:
                - particleGun_E10_Theta9_171.root 
        legTitle:
                - "Photon"
        histName: 
                - electronStudy/OneElectronOnePhoton/trackClusterParallelDistance-Photon1
        legPos:
                - 0.3
                - 0.6
                - 0.68
                - 0.8
        histColor:
                - 1
        xAxisRange:
                - 0
                - 105
        drawOption: HIST
        xAxisLabel: "Parallel Distance [mm]"
        markerStyle:
                - 0

electronTrackClusterPlot3:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/e-_testing/e-/ 
        fileName:
                - particleGun_E10_Theta9_171.root 
        legTitle:
                - "Electron"
        histName: 
                - electronStudy/OneElectronOnePhoton/trackClusterPerpendicularDistance-Electron1
        legPos:
                - 0.3
                - 0.6
                - 0.68
                - 0.8
        histColor:
                - 1
        xAxisRange:
                - 0
                - 105
        drawOption: HIST
        xAxisLabel: "Perpendicular Distance [mm]"
        markerStyle:
                - 0

electronTrackClusterPlot4:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/e-_testing/e-/ 
        fileName:
                - particleGun_E10_Theta9_171.root 
        legTitle:
                - "Photon"
        histName: 
                - electronStudy/OneElectronOnePhoton/trackClusterPerpendicularDistance-Photon1
        legPos:
                - 0.3
                - 0.6
                - 0.68
                - 0.8
        histColor:
                - 1
        xAxisRange:
                - 0
                - 105
        drawOption: HIST
        xAxisLabel: "Perpendicular Distance [mm]"
        markerStyle:
                - 0

