default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_o1_v02/electrons/ 
        fileName:
                - 50mm_trackClusterDistanceCut/eventHists.root
                - 20mm_trackClusterDistanceCut/eventHists.root
                - nominal_withCaloInfo/eventHists.root
        legTitle:
                - "Mod cut (50mm, 50mm)"
                - "Mod cut (20mm, 20mm)"
                - "Nominal cut (3mm, 10mm)"


TrackClusterDistanceCut_effVsEnergy:
        histName: 
                - Graph 
        legPos:
                - 0.2
                - 0.2
                - 0.9
                - 0.5
        xAxisRange:
                - 0
                - 120
        yAxisRange:
                - 0.5
                - 1.0
        drawOption: ALP
        sameDrawOption: LP
        xAxisLabel: "Energy [GeV]"
        yAxisLabel: "Efficiency [%]"

