twoPhotons1:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/e-_testing/e-/ 
        fileName:
                - particleGun_E10_Theta9_171.root 
        legTitle:
                - "Leading Photon"
        histName: 
                - electronStudy/TwoPhotons/trackClusterParallelDistance-Photon1
        legPos:
                - 0.3
                - 0.6
                - 0.68
                - 0.8
        histColor:
                - 1
        xAxisRange:
                - 0
                - 105
        drawOption: HIST
        xAxisLabel: "Parallel Distance [mm]"
        markerStyle:
                - 0

twoPhotons2:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/e-_testing/e-/ 
        fileName:
                - particleGun_E10_Theta9_171.root 
        legTitle:
                - "Subleading Photon"
        histName: 
                - electronStudy/TwoPhotons/trackClusterParallelDistance-Photon2
        legPos:
                - 0.3
                - 0.6
                - 0.68
                - 0.8
        histColor:
                - 1
        xAxisRange:
                - 0
                - 105
        drawOption: HIST
        xAxisLabel: "Parallel Distance [mm]"
        markerStyle:
                - 0

twoPhotons3:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/e-_testing/e-/ 
        fileName:
                - particleGun_E10_Theta9_171.root 
        legTitle:
                - "Leading Photon"
        histName: 
                - electronStudy/TwoPhotons/trackClusterPerpendicularDistance-Photon1
        legPos:
                - 0.3
                - 0.6
                - 0.68
                - 0.8
        histColor:
                - 1
        xAxisRange:
                - 0
                - 105
        drawOption: HIST
        xAxisLabel: "Perpendicular Distance [mm]"
        markerStyle:
                - 0

twoPhotons4:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/e-_testing/e-/ 
        fileName:
                - particleGun_E10_Theta9_171.root 
        legTitle:
                - "Subleading Photon"
        histName: 
                - electronStudy/TwoPhotons/trackClusterPerpendicularDistance-Photon2
        legPos:
                - 0.3
                - 0.6
                - 0.68
                - 0.8
        histColor:
                - 1
        xAxisRange:
                - 0
                - 105
        drawOption: HIST
        xAxisLabel: "Perpendicular Distance [mm]"
        markerStyle:
                - 0

