energy_corrections:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/build/PhotonECAL/FCCee_singleParticle_performace/kaon0L/nominalEfficiency/test/
        fileName:
                - particleGun_E50_Theta47_Phi0.root
        legTitle:
                # - neutral PFO
                - photon PFO
                - Corrected PFO Energy (Hadron constants)
        histName: 
                # - PandoraPFOs_2112/signalPFO_noAdditionalPFOs/Energy
                - PandoraPFOs_22/signalPFO_noAdditionalPFOs/Energy
                - PandoraPFOs_22/signalPFO_noAdditionalPFOs_clusterInfo/TestCorrectedEnergy
        legPos:
                - 0.12
                - 0.7
                - 0.88
                - 0.9
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        xAxisRange:
                - 0
                - 65
        yAxisRange:
                - 0
                - 50
        histTitle: "K^{0}_{L} gun, E: 50 GeV, Theta: 46-48"
        legCaptionMode: mean
