default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/ 
                # - oldRootFiles/hist_Zuds91.root
        # legTitle:
        #         - "Nominal"
        #         - "20mm cut"
        #         - "50mm cut"
                # - "OLD RESULTS (cross check)"
        markerStyle:
                - 0
                - 0
                - 0
        rebinFactor: 8
        legCaptionMode: mean
        xAxisRange:
                - 0
                - 400
        drawOption: HIST
        xAxisLabel: "Energy [GeV]"
        yAxisLabel: "Counts"
        legPos:
                - 0.45
                - 0.6
                - 0.9
                - 0.9


TrackClusterDistanceCut_Zuds380_photonRecoEnergy:
        fileName:
                - nominal_trackClusterDistance/hist_Zuds380.root
                - 20mm_trackClusterDistance/hist_Zuds380.root
                - 50mm_trackClusterDistance/hist_Zuds380.root
        legTitle:
                - "Nominal"
                - "20mm cut"
                - "50mm cut"
        histName: 
                - hist_pfoEnergyPhotons  

TrackClusterDistanceCut_Zuds380_photonEnergyRecoVsTruth:
        fileName:
                - nominal_trackClusterDistance/hist_Zuds380.root
        legTitle:
                - "Truth"
                - "Nominal"
        histName: 
                - hist_pfoTargetsEnergyPhotons
                - hist_pfoEnergyPhotons  

TrackClusterDistanceCut_Zuds380_neutralRecoEnergy:
        fileName:
                - nominal_trackClusterDistance/hist_Zuds380.root
                - 20mm_trackClusterDistance/hist_Zuds380.root
                - 50mm_trackClusterDistance/hist_Zuds380.root
        legTitle:
                - "Nominal"
                - "20mm cut"
                - "50mm cut"
        histName: 
                - hist_pfoEnergyNeutralHadrons  

TrackClusterDistanceCut_Zuds380_neutralEnergyRecoVsTruth:
        fileName:
                - nominal_trackClusterDistance/hist_Zuds380.root
        legTitle:
                - "Truth"
                - "Nominal"
        histName: 
                - hist_pfoTargetsEnergyNeutralHadrons
                - hist_pfoEnergyNeutralHadrons

TrackClusterDistanceCut_Zuds380_tracksRecoEnergy:
        fileName:
                - nominal_trackClusterDistance/hist_Zuds380.root
                - 20mm_trackClusterDistance/hist_Zuds380.root
                - 50mm_trackClusterDistance/hist_Zuds380.root
        legTitle:
                - "Nominal"
                - "20mm cut"
                - "50mm cut"
        histName: 
                - hist_pfoEnergyTracks  
        xAxisRange:
                - 0
                - 500
        legPos:
                - 0.6
                - 0.7
                - 0.9
                - 0.9

TrackClusterDistanceCut_Zuds380_tracksEnergyRecoVsTruth:
        fileName:
                - nominal_trackClusterDistance/hist_Zuds380.root
        legTitle:
                - "Truth"
                - "Nominal"
        histName: 
                - hist_pfoTargetsEnergyTracks
                - hist_pfoEnergyTracks
        xAxisRange:
                - 0
                - 500
        legPos:
                - 0.6
                - 0.7
                - 0.9
                - 0.9

TrackClusterDistanceCut_Zuds380_totalRecoEnergy:
        fileName:
                - nominal_trackClusterDistance/hist_Zuds380.root
                - 20mm_trackClusterDistance/hist_Zuds380.root
                - 50mm_trackClusterDistance/hist_Zuds380.root
        legTitle:
                - "Nominal"
                - "20mm cut"
                - "50mm cut"
        histName: 
                - hist_pfoEnergyTotal  
        legPos:
                - 0.2
                - 0.6
                - 0.6
                - 0.9
        xAxisRange:
                - 200
                - 450

TrackClusterDistanceCut_Zuds380_totalEnergyRecoVsTruth:
        fileName:
                - nominal_trackClusterDistance/hist_Zuds380.root
        legTitle:
                - "Truth"
                - "Nominal"
        histName: 
                - hist_pfoTargetsEnergyTotal
                - hist_pfoEnergyTotal
        legPos:
                - 0.2
                - 0.6
                - 0.6
                - 0.9
        xAxisRange:
                - 200
                - 450

