default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/ 
                # - oldRootFiles/hist_Zuds91.root
        # legTitle:
        #         - "Nominal"
        #         - "20mm cut"
        #         - "50mm cut"
                # - "OLD RESULTS (cross check)"
        markerStyle:
                - 0
                - 0
                - 0
        rebinFactor: 8
        legCaptionMode: mean
        xAxisRange:
                - 0
                - 400
        drawOption: HIST
        xAxisLabel: "Energy [GeV]"
        yAxisLabel: "Counts"
        legPos:
                - 0.45
                - 0.6
                - 0.9
                - 0.9

TrackClusterDistanceCut_Zuds500_photonEnergyRecoVsTruth:
        fileName:
                - CLIC_nominal_Zuds500/hist_Zuds500.root
        legTitle:
                - "Truth"
                - "Nominal"
        histName: 
                - hist_pfoTargetsEnergyPhotons
                - hist_pfoEnergyPhotons  

TrackClusterDistanceCut_Zuds500_neutralEnergyRecoVsTruth:
        fileName:
                - CLIC_nominal_Zuds500/hist_Zuds500.root
        legTitle:
                - "Truth"
                - "Nominal"
        histName: 
                - hist_pfoTargetsEnergyNeutralHadrons
                - hist_pfoEnergyNeutralHadrons

TrackClusterDistanceCut_Zuds500_tracksEnergyRecoVsTruth:
        fileName:
                - CLIC_nominal_Zuds500/hist_Zuds500.root
        legTitle:
                - "Truth"
                - "Nominal"
        histName: 
                - hist_pfoTargetsEnergyTracks
                - hist_pfoEnergyTracks
        xAxisRange:
                - 0
                - 500
        legPos:
                - 0.6
                - 0.7
                - 0.9
                - 0.9

TrackClusterDistanceCut_Zuds500_totalEnergyRecoVsTruth:
        fileName:
                - CLIC_nominal_Zuds500/hist_Zuds500.root
        legTitle:
                - "Truth"
                - "Nominal"
        histName: 
                - hist_pfoTargetsEnergyTotal
                - hist_pfoEnergyTotal
        legPos:
                - 0.2
                - 0.6
                - 0.6
                - 0.9
        xAxisRange:
                - 200
                - 450

