FCCee_dPhi_1:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/e-/codeTest_jan16/ 
        fileName:
                - particleGun_E5.root
                - particleGun_E5_Theta85_95.root
                - particleGun_E5_Theta30_40.root
        legTitle:
                - "full theta range"
                - "theta: 89-95"
                - "theta: 30-40"
        histName: 
                - PandoraPFOs_11/signalPFO_secondEnergeticPFO/dPhi 
        legPos:
                - 0.12
                - 0.75
                - 0.48
                - 0.88
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        xAxisRange:
                - -50
                - 50
        # yAxisRange:
        #         - 0.0
        #         - 2000
        histTitle: "electron-photon distance , E=5 GeV"
        # legCaptionMode: entries
        # logY: 1
        rebinFactor: 1
        # scaleFactor: 0.25
        drawOptions: H
        # yAxisLabel: Counts
        # xAxisLabel: "#phi_{true} - #phi_{reco} [rad]"
