default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/ 
        legTitle:
                - "CLICdet"
                - "CLD"
        histName:
                # - eventHists/efficiencyVsCosThetaCat2
                - eventHists/efficiencyVsCosTheta
        legPos:
                - 0.3
                - 0.3
                - 0.8
                - 0.5
        yAxisRange:
                - 0.0
                - 1.1
        drawOption: HIST
        yAxisLabel: Efficiency
        markerStyle:
                - 0
                - 0
        rebinFactor: 2
        scaleFactor: 0.5

calice_CLIC_vs_FCCee_effVsTheta_pions_E5:
        fileName:
                - CLIC_o3_v14/pions/particleGun_E5_Theta9_171.root
                - FCCee_o1_v02/pions/particleGun_E5_Theta9_171.root

calice_CLIC_vs_FCCee_effVsTheta_pions_E100:
        fileName:
                - CLIC_o3_v14/pions/particleGun_E100_Theta9_171.root
                - FCCee_o1_v02/pions/particleGun_E100_Theta9_171.root
#
calice_CLIC_vs_FCCee_effVsTheta_pions_E50:
        fileName:
                - CLIC_o3_v14/pions/particleGun_E50_Theta9_171.root
                - FCCee_o1_v02/pions/particleGun_E50_Theta9_171.root

calice_CLIC_vs_FCCee_effVsTheta_pions_E20:
        fileName:
                - CLIC_o3_v14/pions/particleGun_E20_Theta9_171.root
                - FCCee_o1_v02/pions/particleGun_E20_Theta9_171.root

calice_CLIC_vs_FCCee_effVsTheta_pions_E10:
        fileName:
                - CLIC_o3_v14/pions/particleGun_E10_Theta9_171.root
                - FCCee_o1_v02/pions/particleGun_E10_Theta9_171.root


#
#
#
#
#
# # calice_CLIC_vs_FCCee_effVsTheta_pions_E2:
# #         fileName:
# #                 - CLIC_o3_v14/pions/particleGun_E2_Theta9_171.root
#                 # - FCCee_o1_v02/pions/particleGun_E2_Theta9_171.root
#
# # calice_CLIC_vs_FCCee_effVsTheta_pions_E1:
# #         fileName:
# #                 - CLIC_o3_v14/pions/particleGun_E1_Theta9_171.root
# #                 - FCCee_o1_v02/pions/particleGun_E1_Theta9_171.root
#
#
