photon_eff_vs_theta_E100:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/gamma/newAngularRequirements/
        fileName:
                - particleGun_E100_Theta9_171.root
        legTitle:
                - no photon convertion events
                - nominal efficiency
                - photon PFO reclustering
                # - photon+neutral reclustering
                # - photon+neutral PFO reclustering (looser cut)
                - photon+neutral PFO reclustering
        histName: 
                - eventHists_noConv/efficiencyVsCosTheta
                - eventHists/efficiencyVsCosTheta
                # - eventHists_conv/efficiencyVsCosTheta
                - eventHists_photonRecl/efficiencyVsCosTheta
                # - eventHists_photonAndNeutralRecl/efficiencyVsCosTheta
                - eventHists_photonAndNeutralRecl_looseThetaCut/efficiencyVsCosTheta
                # - eventHists_noFSR/efficiencyVsCosTheta
                # - eventHists_photonMerge/efficiencyVsCosTheta
                # - eventHists_photonAndNeutralLooseMerge/efficiencyVsCosTheta
                # - eventHists_photonReclMomDep/efficiencyVsCosTheta
        legPos:
                - 0.2
                - 0.7
                - 0.7
                - 0.9
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        # xAxisRange:
        #         - 0
        #         - 120
        yAxisRange:
                - 0.0
                - 1.5
        histTitle: "E_{e}=100 GeV"
        # legCaptionMode: entries
        # logY: 1
        rebinFactor: 4
        scaleFactor: 0.25
        # drawOption: HIST
        drawOption: E1
        yAxisLabel: Efficiency
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0
