default:
        fileName:
                - nominal_trackClusterDistance/hist_Zuds91.root
                - FCCee_extendedEcalEndcap/hist_Zuds91.root
        legTitle:
                - "FCCee"
                - "FCCee: extended ECAL endcap"
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/ 
        markerStyle:
                - 0
                - 0
                - 0



TrackClusterDistanceCut_resolutionVsCosTheta_Zuds380_nomVs20:
        histName:
                - ResVsCosTheta
        legPos:
                - 0.2
                - 0.6
                - 0.85
                - 0.9
        yAxisRange:
                - 3
                - 7

