jet_eRes_FCCee_CLIC_91:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/python/rootFiles/
        fileName:
                - hist_Zuds91.root
                - CLIC_jet_eRes_oct18_Zuds91.root
        legTitle:
                - FCCee Zuds 91 GeV
                - CLIC Zuds 91 GeV
        histName: 
                - ResVsCosTheta
        legPos:
                - 0.12
                - 0.7
                - 0.88
                - 0.9
        histColor:
                - 1
                - 2
        yAxisRange:
                - 3
                - 7.5
jet_eRes_FCCee_CLIC_380:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/python/rootFiles/
        fileName:
                - hist_Zuds380.root
                - CLIC_jet_eRes_oct18_Zuds380.root
        legTitle:
                - FCCee Zuds 380 GeV
                - CLIC Zuds 380 GeV
        histName: 
                - ResVsCosTheta
        legPos:
                - 0.12
                - 0.7
                - 0.88
                - 0.9
        histColor:
                - 1
                - 2
        yAxisRange:
                - 3
                - 7.5
