default:
        drawOption: P
        sameDrawOption: LP
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_o1_v03/bbbar/singlePart/
        canPos:
                - 0
                - 0
                - 800
                - 800
        # yAxisTitleOffset: 0.9
        yAxisRange:
                - 0.0
                - 1.0
        # markerSize: 1.6
        fileName:
                - muonRecoMisID_vertexOffsetX_10mm_50GeV.root
                - muonRecoMisID_vertexOffsetX_5mm_50GeV.root
        # gridX: 1
        # gridY: 1
        # legPos:
        #         - 0.5
        #         - 0.7
        #         - 0.85
        #         - 0.9
        # legTitle:
        #         - R=10mm
        #         - R=15mm
                # - relaxed cuts
        yAxisLabel: "Efficiency"

muonEff_temp_vertexR:
        histName: 
                - muonEffInJets/eff_truthPartMatched/vertexR
        rebinFactor: 2
        scaleFactor: 0.5
        xAxisLabel: "Vertex R [mm]"
        
