default:
        drawOption: HIST
        sameDrawOption: HIST  
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_o1_v03/pionMuonMisReco/ 
        canPos:
                - 0
                - 0
                - 800
                - 800
        # yAxisTitleOffset: 0.9
        # yAxisRange:
        #         - 0.0
        #         - 8.0
        # markerSize: 1.6
        # gridX: 1
        # gridY: 1
        legPos:
                - 0.3
                - 0.7
                - 0.85
                - 0.9
        histName: 
                - muonClusterFiller/cluster/nYokeHits
        normalize: True
        xAxisRange:
                - 0
                - 120

muonPionMisID_nYokeHits_nominalConeRequirements:
        fileName:
                - jun20_nominalConeRequirements/muonSample/muonRecoMisID_E99_101.root
                - jun20_nominalConeRequirements/pionSample/muonRecoMisID_E99_101.root
        xAxisLabel: "nHits"
        legCaptionMode: mean
        legTitle:
                - muon sample
                - pion sample 

muonPionMisID_nYokeHits_relaxedConeRequirements:
        fileName:
                - jun20_relaxedConeRequirements/muonSample/muonRecoMisID_E99_101.root
                - jun20_relaxedConeRequirements/pionSample/muonRecoMisID_E99_101.root
        xAxisLabel: "nHits"
        legCaptionMode: mean
        legTitle:
                - muon sample
                - pion sample 

muonPionMisID_nYokeHits_relaxed_vs_nominal_pionSample:
        fileName:
                - jun20_nominalConeRequirements/pionSample/muonRecoMisID_E99_101.root
                - jun20_relaxedConeRequirements/pionSample/muonRecoMisID_E99_101.root
        xAxisLabel: "nHits"
        legCaptionMode: mean
        legTitle:
                - nominal cone requirements
                - relaxed cone requirements

muonPionMisID_nYokeHits_relaxed_vs_nominal_muonSample:
        fileName:
                - jun20_nominalConeRequirements/muonSample/muonRecoMisID_E99_101.root
                - jun20_relaxedConeRequirements/muonSample/muonRecoMisID_E99_101.root
        xAxisLabel: "nHits"
        legCaptionMode: mean
        legTitle:
                - nominal cone requirements
                - relaxed cone requirements
                  
muonPionMisID_nYokeHits_relaxed_vs_nominal_pionSample:
        fileName:
                - jun20_nominalConeRequirements/pionSample/muonRecoMisID_E99_101.root
                - jun20_relaxedConeRequirements/pionSample/muonRecoMisID_E99_101.root
                - jun20_relaxedConeRequirements_v2/pionSample/muonRecoMisID_E99_101.root
        xAxisLabel: "nHits"
        legCaptionMode: mean
        legTitle:
                - nominal cone requirements
                - relaxed cone requirements
                - relaxed cone requirements v2
