default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/scripts/softwareCompensationWeightsPlotter/ 
        legTitle:
                - "2-200 GeV"
                # - "2-150 GeV"
                - "2-100 GeV"
                - "2-75 GeV"
                - "ILD"
                - "CLIC"
        histName: 
                - Graph 
        legPos:
                - 0.5
                - 0.6
                - 0.9
                - 0.9
        xAxisRange:
                - 0
                - 40
        yAxisRange:
                - 0.0
                - 3.0
        drawOption: ALP
        sameDrawOption: LP
        xAxisLabel: "Hit Energy Density [GeV/1000 cm^{3}]"
        yAxisLabel: "Weight value"


may29_SWC_weights_1_GeV:
        fileName:
                - SWC_FCCee_E1.root
                # - SWC_FCCee_no200_E1.root
                - SWC_FCCee_no150_no200_E1.root
                - SWC_FCCee_no100_no150_no200_E1.root
                - SWC_ILD_E1.root
                - SWC_CLIC_E1.root

may29_SWC_weights_5_GeV:
        fileName:
                - SWC_FCCee_E5.root
                # - SWC_FCCee_no200_E5.root
                - SWC_FCCee_no150_no200_E5.root
                - SWC_FCCee_no100_no150_no200_E5.root
                - SWC_ILD_E5.root
                - SWC_CLIC_E5.root

may29_SWC_weights_10_GeV:
        fileName:
                - SWC_FCCee_E10.root
                # - SWC_FCCee_no200_E10.root
                - SWC_FCCee_no150_no200_E10.root
                - SWC_FCCee_no100_no150_no200_E10.root
                - SWC_ILD_E10.root
                - SWC_CLIC_E10.root

may29_SWC_weights_30_GeV:
        fileName:
                - SWC_FCCee_E30.root
                # - SWC_FCCee_no200_E30.root
                - SWC_FCCee_no150_no200_E30.root
                - SWC_FCCee_no100_no150_no200_E30.root
                - SWC_ILD_E30.root
                - SWC_CLIC_E30.root

may29_SWC_weights_90_GeV:
        fileName:
                - SWC_FCCee_E90.root
                # - SWC_FCCee_no200_E90.root
                - SWC_FCCee_no150_no200_E90.root
                - SWC_FCCee_no100_no150_no200_E90.root
                - SWC_ILD_E90.root
                - SWC_CLIC_E90.root

# may29_SWC_weights_50_GeV:
#         fileName:
#                 - SWC_FCCee_E50.root
#                 - SWC_FCCee_no200_E50.root
#                 - SWC_FCCee_no150_no200_E50.root
#                 - SWC_FCCee_no100_no150_no200_E50.root
#
# may29_SWC_weights_70_GeV:
#         fileName:
#                 - SWC_FCCee_E70.root
#                 - SWC_FCCee_no200_E70.root
#                 - SWC_FCCee_no150_no200_E70.root
#                 - SWC_FCCee_no100_no150_no200_E70.root
#
#
#
