default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/TEMPLATES/
        legPos:
                - 0.2
                - 0.7
                - 0.58
                - 0.9
        yAxisRange:
                - 2.5
                - 8
        yAxisTitleOffset: 0.95
        # skipMissingHists: 1


jun7_Zuds91_CT_vs_TT:
        legTitle:
                - "Conformal Tracking"
                - "Truth Tracking"
        histName: 
                - ResVsCosTheta
        fileName:
                - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E91_ConformalTr_run1_files/hists.root
                - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E91_TruthTr_run1_files/hists.root
jun7_Zuds380_CT_vs_TT:
        legTitle:
                - "Conformal Tracking"
                - "Truth Tracking"
        histName: 
                - ResVsCosTheta
        fileName:
                - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E380_ConformalTr_run1_files/hists.root
                - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E380_TruthTr_run1_files/hists.root

jun7_Zuds91_CTnew_vs_CTold:
        legTitle:
                - "Conformal Tracking (2018-05-18)"
                - "Conformal Tracking (2018-04-26)"
                - "Conformal Tracking (MHHHE)"
        histName: 
                - ResVsCosTheta
        fileName:
                - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E91_ConformalTr_run1_files/hists.root
                - ../../../../../../../../../ssd/viazlo/data/Zuds_SWC_noSWC_MHHE/FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E91_ConformalTr.root 
                - ../../../../../../../../../ssd/viazlo/data/Zuds_SWC_noSWC_MHHE/FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_MHHHE_ZudsSample_E91_ConformalTr.root 
jun7_Zuds380_CTnew_vs_CTold:
        legTitle:
                - "Conformal Tracking (2018-05-18)"
                - "Conformal Tracking (2018-04-26)"
                - "Conformal Tracking (MHHHE)"
        histName: 
                - ResVsCosTheta
        fileName:
                - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E380_ConformalTr_run1_files/hists.root
                - ../../../../../../../../../ssd/viazlo/data/Zuds_SWC_noSWC_MHHE/FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E380_ConformalTr.root 
                - ../../../../../../../../../ssd/viazlo/data/Zuds_SWC_noSWC_MHHE/FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_MHHHE_ZudsSample_E380_ConformalTr.root 
                  
jun7_Zuds91_vs_Zuds380:
        legTitle:
                - "45.5 GeV Jets"
                - "190 GeV Jets"
        histName: 
                - ResVsCosTheta
        fileName:
                - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E91_ConformalTr_run1_files/hists.root
                - FCCee_o1_v03_ILCSoft-2018-05-18_gcc62_SinglePart_gamma_E380_ConformalTr_run1_files/hists.root
        yAxisRange:
                - 3 
                - 7.5
