default:
        drawOption: ALP
        sameDrawOption: LP
        sortXaxisInGraph: True
        dirPrefix: /afs/cern.ch/work/v/viazlo/scripts/makeResolutionPlot/ 
        histName: 
                - Graph
        lineWidth: 0
        # histColor:
        #         - 1
        #         - 2
        #         - 8
        #         - 12
        canPos:
                - 0
                - 0
                - 800
                - 800
        yAxisLabel: "#sigma(E_{PFO})/E_{PFO} [%]"
        yAxisTitleOffset: "0.9"
        xAxisLabel: Energy [GeV]
        yAxisRange:
                - 0.0
                - 8.0
        markerSize: 1.0

jun7_photonRes_barrel_vs_full:
        gridX: 1
        gridY: 1
        fileName:
                - theta_range_50_130/ecalRes.root
                - whole_theta_range/ecalRes.root
        legTitle:
                - "#theta: 50#circ-130#circ"
                - "#theta: 9#circ-171#circ"
        legPos:
                - 0.5
                - 0.7
                - 0.85
                - 0.9
        histTitle: "TEST"

