default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/materialScan/dataFiles/ 
        histName: 
                - hist_-1 
        yAxisLabel: "Material Budget [#lambda_{I}]"
        xAxisLabel: "#theta [^{o}]"
        markerStyle:
                - 0
                - 0
                - 0
                - 0
        legPos:
                - 0.6
                - 0.7
                - 0.9
                - 0.9

materialBudget_fccee_extendedEcalEndcap:
        fileName:
                # - clic_ECAL_forComparison.root
                # - fccee_ECAL_forComparison.root
                # - fccee_ECAL_forComparison_mod_v1.root
                # - fccee_ECAL_forComparison_mod_v2.root
                # - fccee_ECAL_extendedEcalEndcap.root
                - fcc_HCAL.root
                - fccee_HCAL_extendedEcalEndcap.root
        legTitle:
                - "old hcal"
                # - "fix old"
                - "fix new"
        yAxisRange:
                - 0
                - 10


materialBudget_fccee_vs_clic:
        fileName:
                - clic_ECAL_forComparison.root
                - fccee_ECAL_forComparison.root
                # - fccee_ECAL_forComparison_mod_v1.root
                # - fccee_ECAL_forComparison_mod_v2.root
        legTitle:
                - "CLIC"
                - "CLD"
                # - "fccee mod v1"
                # - "CLD: extended ECAL endcap"
        # scaleFactor: 100
        yAxisRange:
                - 0
                - 2
