default:
        fileName:
                - Zuds_TT_vs_CT_Old_VT_vs_noSWC_180302_correctMC_finalhistos_DR_Studies_histoFitRange_0_75_to_1_25_RedXRange_centralQuark_cosTheta_0_70_mean90Histo.root 
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/Matthias/
        markerStyle:
                - 0
                - 0
                - 0
        legPos:
                - 0.2
                - 0.2
                - 0.85
                - 0.4

matthias_SWC_linearity:
        histName:
                - t_E_CT_Old_summary_91_to_3000_Mean90_d1_cosT_0_70
                - t_E_CT_noSWC_summary_91_to_3000_Mean90_d1_cosT_0_70
        legTitle:
                - with Software Compensation
                - w/o Software Compensation
        yAxisRange:
                - 0.95
                - 1.05
        xAxisLabel: "E_{jet} [GeV]"
        yAxisLabel: "Mean_{90} (E^{reco}_{tot}/E^{true}_{tot})"
        yAxisTitleOffset: 1.13

