default:
        dirPrefix: /ssd/viazlo/data/Zuds_SWC_noSWC_MHHE/ 
        legPos:
                - 0.2
                - 0.7
                - 0.58
                - 0.9
        yAxisRange:
                - 2.5
                - 7.5
        yAxisTitleOffset: 0.95
        skipMissingHists: 1
        legTitle:
                - CLD (FCCee)
                - CLICdet



JER_FCCee_vs_CLIC_conformal_Zuds91_matthiasCLIC:
        histName: 
                - ResVsCosTheta
                - JER_RMS90VsCosTheta_CT_Old_91
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E91_ConformalTr.root 
                - Matthias/Zuds_TT_vs_CT_Old_VT_vs_noSWC_180302_correctMC_finalhistos_DR_Studies_histoFitRange_0_75_to_1_25_RedXRange_centralQuark_cosTheta_0_70_mean90Histo.root

JER_FCCee_vs_CLIC_conformal_Zuds91_myCLIC:
        histName: 
                - ResVsCosTheta
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E91_ConformalTr.root 
                - hist_myPandoraAnalysis_Zuds_ZudsSample_E91_ConformalTr.root

JER_FCCee_vs_CLIC_conformal_Zuds100_matthiasCLIC:
        histName: 
                - ResVsCosTheta
                - JER_RMS90VsCosTheta_CT_Old_100
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E100_ConformalTr.root 
                - Matthias/Zuds_TT_vs_CT_Old_VT_vs_noSWC_180302_correctMC_finalhistos_DR_Studies_histoFitRange_0_75_to_1_25_RedXRange_centralQuark_cosTheta_0_70_mean90Histo.root

JER_FCCee_vs_CLIC_conformal_Zuds100_myCLIC:
        histName: 
                - ResVsCosTheta
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E100_ConformalTr.root 
                - hist_myPandoraAnalysis_Zuds_ZudsSample_E100_ConformalTr.root
                  
JER_FCCee_vs_CLIC_conformal_Zuds200_matthiasCLIC:
        histName: 
                - ResVsCosTheta
                - JER_RMS90VsCosTheta_CT_Old_200
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E200_ConformalTr.root 
                - Matthias/Zuds_TT_vs_CT_Old_VT_vs_noSWC_180302_correctMC_finalhistos_DR_Studies_histoFitRange_0_75_to_1_25_RedXRange_centralQuark_cosTheta_0_70_mean90Histo.root

JER_FCCee_vs_CLIC_conformal_Zuds200_myCLIC:
        histName: 
                - ResVsCosTheta
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E200_ConformalTr.root 
                - hist_myPandoraAnalysis_Zuds_ZudsSample_E200_ConformalTr.root

JER_FCCee_vs_CLIC_conformal_Zuds380_matthiasCLIC:
        histName: 
                - ResVsCosTheta
                - JER_RMS90VsCosTheta_CT_Old_380
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E380_ConformalTr.root 
                - Matthias/Zuds_TT_vs_CT_Old_VT_vs_noSWC_180302_correctMC_finalhistos_DR_Studies_histoFitRange_0_75_to_1_25_RedXRange_centralQuark_cosTheta_0_70_mean90Histo.root

JER_FCCee_vs_CLIC_conformal_Zuds380_myCLIC:
        histName: 
                - ResVsCosTheta
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E380_ConformalTr.root 
                - hist_myPandoraAnalysis_Zuds_ZudsSample_E380_ConformalTr.root 

