default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_o1_v03/pions/pionMuonMisReco/ 
        legTitle:
                - "nominal efficiency"
                - "type mismatch"
                - "mismatch an neutral particle"
                - "mismatch as muon"
                - "mismatch as electron"
        histName: 
                - eventHists/efficiencyVsCosTheta
                - eventHists/efficiencyVsCosThetaFailType/all
                - eventHists/efficiencyVsCosThetaFailType/noChargedParts
                - eventHists/efficiencyVsCosThetaFailType/onlyMuon
                - eventHists/efficiencyVsCosThetaFailType/onlyElectron
        legPos:
                - 0.3
                - 0.4
                - 0.68
                - 0.6
        # histColor:
        #         - 1
        #         - 2
        #         - 3
        #         - 4
        #         - 5
        #         - 6
        #         - 7
        #         - 8
        # xAxisRange:
        #         - 0
        #         - 120
        yAxisRange:
                - 0.0
                - 1.0
        # legCaptionMode: entries
        # logY: 1
        rebinFactor: 16
        scaleFactor: 0.0625
        drawOption: HIST
        yAxisLabel: Efficiency
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0

pion_eff_vs_theta_E100:
        fileName:
                - particleGun_E100_Theta9_171.root
        histTitle: "E_{pi}=100 GeV"

pion_eff_vs_theta_E100_muonHitRmsCut_5:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_o1_v03/pions/pionMuonMisReco/muonHitRmsCut_5/
        fileName:
                - particleGun_E100_Theta9_171.root
        histTitle: "E_{pi}=100 GeV"
