default:
        dirPrefix: /ssd/viazlo/data/Zuds_SWC_noSWC_MHHE/ 
        legPos:
                - 0.2
                - 0.7
                - 0.8
                - 0.9
        yAxisRange:
                - 2.5
                - 7.5
        yAxisTitleOffset: 0.95
        # skipMissingHists: 1
        fileName:
                - Matthias/Zuds_TT_vs_CT_Old_VT_vs_noSWC_180302_correctMC_finalhistos_DR_Studies_histoFitRange_0_75_to_1_25_RedXRange_centralQuark_cosTheta_0_70_mean90Histo.root



JER_conformal_Zuds50-3000_matthiasCLIC:
        histName: 
                - JER_RMS90VsCosTheta_CT_Old_3000
                - JER_RMS90VsCosTheta_CT_Old_1500
                - JER_RMS90VsCosTheta_CT_Old_500
                - JER_RMS90VsCosTheta_CT_Old_380
                - JER_RMS90VsCosTheta_CT_Old_100
        legTitle:
                - 1500 GeV Jets 
                - 750 GeV Jets 
                - 250 GeV Jets 
                - 190 GeV Jets 
                - 50 GeV Jets 

