default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/scripts/softwareCompensationWeightsPlotter/ 
        legTitle:
                - CLD (FCCee)
                - CLICdet 
                - ILD
        histName: 
                - Graph 
        legPos:
                - 0.5
                - 0.6
                - 0.9
                - 0.9
        xAxisRange:
                - 0
                - 40
        yAxisRange:
                - 0.0
                - 3.0
        drawOption: ALP
        sameDrawOption: LP
        xAxisLabel: "Hit Energy Density [GeV/1000 cm^{3}]"
        yAxisLabel: "Weight value"
        savePictDir: "SWC_weigths"
        legTitle:
            - 'FCCee: 400ns'
            - 'FCCee'
            - CLIC
            - ILD


may29_SWC_weights_1_GeV:
        fileName:
                - SWC_FCCee_2018nov12_E1.root
                - SWC_FCCee_E1.root
                - SWC_CLIC_E1.root
                - SWC_ILD_E1.root

may29_SWC_weights_5_GeV:
        fileName:
                - SWC_FCCee_2018nov12_E5.root
                - SWC_FCCee_E5.root
                - SWC_CLIC_E5.root
                - SWC_ILD_E5.root

may29_SWC_weights_10_GeV:
        fileName:
                - SWC_FCCee_2018nov12_E10.root
                - SWC_FCCee_E10.root
                - SWC_CLIC_E10.root
                - SWC_ILD_E10.root

may29_SWC_weights_30_GeV:
        fileName:
                - SWC_FCCee_2018nov12_E30.root
                - SWC_FCCee_E30.root
                - SWC_CLIC_E30.root
                - SWC_ILD_E30.root

may29_SWC_weights_90_GeV:
        fileName:
                - SWC_FCCee_2018nov12_E90.root
                - SWC_FCCee_E90.root
                - SWC_CLIC_E90.root
                - SWC_ILD_E90.root


