default:
        dirPrefix: /ssd/viazlo/data/Zuds_SWC_noSWC_MHHE/ 
        legPos:
                - 0.2
                - 0.7
                - 0.8
                - 0.9
        yAxisRange:
                - 2.5
                - 7.5
        yAxisTitleOffset: 0.95
        # skipMissingHists: 1
        fileName:
                - Matthias/Zuds_TT_vs_CT_Old_VT_vs_noSWC_180302_correctMC_finalhistos_DR_Studies_histoFitRange_0_75_to_1_25_RedXRange_centralQuark_cosTheta_0_70_mean90Histo.root


JER_SWC_ON_and_OFF_conformal_Zuds91_matthiasCLIC:
        histName: 
                - JER_RMS90VsCosTheta_CT_Old_91
                - JER_RMS90VsCosTheta_CT_noSWC_91
        legTitle:
                - with Software Compensation
                - w/o Software Compensation

JER_SWC_ON_and_OFF_conformal_Zuds380_matthiasCLIC:
        histName: 
                - JER_RMS90VsCosTheta_CT_Old_380
                - JER_RMS90VsCosTheta_CT_noSWC_380
        legTitle:
                - with Software Compensation
                - w/o Software Compensation

JER_SWC_ON_and_OFF_conformal_Zuds1000_matthiasCLIC:
        histName: 
                - JER_RMS90VsCosTheta_CT_Old_1000
                - JER_RMS90VsCosTheta_CT_noSWC_1000
        legTitle:
                - with Software Compensation
                - w/o Software Compensation

JER_SWC_ON_and_OFF_conformal_Zuds1500_matthiasCLIC:
        histName: 
                - JER_RMS90VsCosTheta_CT_Old_1500
                - JER_RMS90VsCosTheta_CT_noSWC_1500
        legTitle:
                - with Software Compensation
                - w/o Software Compensation

