default:
        dirPrefix: /ssd/viazlo/data/Zuds_SWC_noSWC_MHHE/ 
        legPos:
                - 0.2
                - 0.7
                - 0.58
                - 0.9
        yAxisRange:
                - 2.5
                - 6
        yAxisTitleOffset: 0.95
        skipMissingHists: 1



JER_FCCee_vs_CLIC_conformal_Zuds91_matthiasCLIC:
        legTitle:
                - "CLD (FCCee) Software Comp"
                - "CLD (FCCee) MHHHE"
                - "CLICdet"
        histName: 
                - ResVsCosTheta
                - JER_RMS90VsCosTheta_CT_Old_91
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E91_ConformalTr.root 
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_MHHHE_ZudsSample_E91_ConformalTr.root 
                - Matthias/Zuds_TT_vs_CT_Old_VT_vs_noSWC_180302_correctMC_finalhistos_DR_Studies_histoFitRange_0_75_to_1_25_RedXRange_centralQuark_cosTheta_0_70_mean90Histo.root


JER_FCCee_vs_CLIC_conformal_Zuds380_matthiasCLIC:
        legTitle:
                - "CLD (FCCee) Software Comp"
                - "CLD (FCCee) MHHHE"
                - "CLICdet"
        histName: 
                - ResVsCosTheta
                - JER_RMS90VsCosTheta_CT_Old_380
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E380_ConformalTr.root 
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_MHHHE_ZudsSample_E380_ConformalTr.root 
                - Matthias/Zuds_TT_vs_CT_Old_VT_vs_noSWC_180302_correctMC_finalhistos_DR_Studies_histoFitRange_0_75_to_1_25_RedXRange_centralQuark_cosTheta_0_70_mean90Histo.root

JER_FCCee_SWC_vs_MHHHE_conformal_Zuds380_matthiasCLIC:
        legTitle:
                - "CLD (FCCee) Software Comp"
                - "CLD (FCCee) MHHHE"
                - "CLD (FCCee) no energy corrections"
        histName: 
                - ResVsCosTheta
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E380_ConformalTr.root 
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_MHHHE_ZudsSample_E380_ConformalTr.root 
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_SWC_isOFF_ZudsSample_E380_ConformalTr.root 

JER_FCCee_SWC_vs_MHHHE_conformal_Zuds91_matthiasCLIC:
        legTitle:
                - "CLD (FCCee) Software Comp"
                - "CLD (FCCee) MHHHE"
                - "CLD (FCCee) no energy corrections"
        histName: 
                - ResVsCosTheta
        fileName:
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_ZudsSample_E91_ConformalTr.root 
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_MHHHE_ZudsSample_E91_ConformalTr.root 
                - FCCee_o1_v03/hist_myPandoraAnalysis_Zuds_SWC_isOFF_ZudsSample_E91_ConformalTr.root 

