muon_eff_E100:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/mu-_rerun/ 
        fileName:
                # - particleGun_E5_Theta9_171.root
                # - particleGun_E10_Theta9_171.root
                # - particleGun_E20_Theta9_171.root
                - particleGun_E100_Theta9_171.root
        legTitle:
                # - "5 GeV"
                # - "10 GeV"
                # - "20 GeV"
                - "muon efficiency"
        histName: 
                - eventHists/efficiencyVsCosTheta
        legPos:
                - 0.3
                - 0.2
                - 0.68
                - 0.4
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        # xAxisRange:
        #         - 0
        #         - 120
        yAxisRange:
                - 0.5
                - 1.0
        histTitle: "E_{e}=100 GeV"
        # legCaptionMode: entries
        # logY: 1
        rebinFactor: 4
        scaleFactor: 0.25
        drawOption: E1
        yAxisLabel: Efficiency
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0

muon_eff_E10:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/mu-_rerun/ 
        fileName:
                # - particleGun_E5_Theta9_171.root
                - particleGun_E10_Theta9_171.root
                # - particleGun_E20_Theta9_171.root
                # - particleGun_E100_Theta9_171.root
        legTitle:
                # - "5 GeV"
                # - "10 GeV"
                # - "20 GeV"
                # - "100 GeV"
                - muon efficiency
        histName: 
                - eventHists/efficiencyVsCosTheta
        legPos:
                - 0.3
                - 0.2
                - 0.68
                - 0.4
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        # xAxisRange:
        #         - 0
        #         - 120
        yAxisRange:
                - 0.5
                - 1.0
        histTitle: "E_{e}=100 GeV"
        # legCaptionMode: entries
        # logY: 1
        rebinFactor: 4
        scaleFactor: 0.25
        drawOption: E1
        yAxisLabel: Efficiency
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0
