default:
    dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/performance/
    legPos:
        - 0.2
        - 0.76
        - 0.8
        - 0.9
    yAxisTitleOffset: 0.95
    textLabel:
        pos:
        - 0.9
        - 1.02
        title: CLD
    yAxisRange:
        - 0.02 
        - 0.10
    savePictDir: "JER_fitting"


# JER_fitting_91GeV:
#     histName:
#         - "hist: resolution"
#     fileName:
#         - 91GeV_noParLimit/hists.root
#         - 91GeV_useParLimit/hists.root
#         - 91GeV_400ns_useParLimit/hists.root
#         - 91GeV_400ns_noParLimit/hists.root
#     legTitle:
#         - "noParLimit"
#         - "useParLimit"
#         - "400ns_useParLimit"
#         - "400ns_noParLimit"
#
# JER_fitting_365GeV:
#     histName:
#         - "hist: resolution"
#     fileName:
#         - 365GeV_noParLimit/hists.root
#         - 365GeV_useParLimit/hists.root
#         - 365GeV_400ns_useParLimit/hists.root
#         - 365GeV_400ns_noParLimit/hists.root
#     legTitle:
#         - "noParLimit"
#         - "useParLimit"
#         - "400ns_useParLimit"
#         - "400ns_noParLimit"

JER_fitting_91_vs_365GeV:
    histName: 
        - "hist: resolution" 
    # fileName:
    #     - 91GeV_400ns_useParLimit/hists.root
    #     - 365GeV_400ns_useParLimit/hists.root
    # legTitle:
    #     - "91GeV_400ns_useParLimit"
    fileName:
        - 91GeV_400ns_st2/hists.root
        - 365GeV_400ns_st2/hists.root
    legTitle:
        - "91GeV_400ns_st2"
        - "365GeV_400ns_st2"
    #     - "365GeV_400ns_useParLimit"

JER_RMS90_91_vs_365GeV:
    dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/TEMPLATES/
    histName: 
        - jetClustering/ResVsCosTheta
    fileName:
        # - FCCee_o1_v03_ILCSoft-2018-10-11_gcc62_zuds_E91.2_ConformalTr_400ns_run1_files/DR11_hists.root
        # - FCCee_o1_v03_ILCSoft-2018-10-11_gcc62_zuds_E365_ConformalTr_400ns_run1_files/DR11_hists.root
        - FCCee_o1_v03_ILCSoft-2018-10-11_gcc62_zuds_E91.2_ConformalTr_400ns_Overlay_run1_files/DR11_180bins.root
        - FCCee_o1_v03_ILCSoft-2018-10-11_gcc62_zuds_E365_ConformalTr_400ns_Overlay_run2_files/DR11_180bins.root
    legTitle:
        - "91GeV_400ns_RMS90"
        - "365GeV_400ns_RMS90"
    yAxisRange:
        - 2.0 
        - 10.0
