nPFOs_vs_theta_pion_E5:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/pi-_noAngNoMomMatching/ 
        fileName:
                - particleGun_E5_Theta9_171.root
        legTitle:
                - "Electron"
                - "Photon"
                - "Pion"
                - "NeutralHadron"
                - "Muon"
                - "All"
        histName:
                - eventHists/nPFOsVsCosTheta/Electron
                - eventHists/nPFOsVsCosTheta/Photon
                - eventHists/nPFOsVsCosTheta/Pion
                - eventHists/nPFOsVsCosTheta/NeutralHadron
                - eventHists/nPFOsVsCosTheta/Muon
                - eventHists/nPFOsVsCosTheta/all
        legPos:
                - 0.35
                - 0.7
                - 0.65
                - 0.9
        yAxisRange:
                - 0.0
                - 1.5
        rebinFactor: 4
        scaleFactor: 0.25
        drawOption: HIST
        yAxisLabel: nPFOs
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
nPFOs_vs_theta_pion_E10:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/pi-_noAngNoMomMatching/ 
        fileName:
                - particleGun_E10_Theta9_171.root
        legTitle:
                - "Electron"
                - "Photon"
                - "Pion"
                - "NeutralHadron"
                - "Muon"
                - "All"
        histName:
                - eventHists/nPFOsVsCosTheta/Electron
                - eventHists/nPFOsVsCosTheta/Photon
                - eventHists/nPFOsVsCosTheta/Pion
                - eventHists/nPFOsVsCosTheta/NeutralHadron
                - eventHists/nPFOsVsCosTheta/Muon
                - eventHists/nPFOsVsCosTheta/all
        legPos:
                - 0.35
                - 0.7
                - 0.65
                - 0.9
        yAxisRange:
                - 0.0
                - 1.5
        rebinFactor: 4
        scaleFactor: 0.25
        drawOption: HIST
        yAxisLabel: nPFOs
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
nPFOs_vs_theta_pion_E2:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/pi-_noAngNoMomMatching/ 
        fileName:
                - particleGun_E2_Theta9_171.root
        legTitle:
                - "Electron"
                - "Photon"
                - "Pion"
                - "NeutralHadron"
                - "Muon"
                - "All"
        histName:
                - eventHists/nPFOsVsCosTheta/Electron
                - eventHists/nPFOsVsCosTheta/Photon
                - eventHists/nPFOsVsCosTheta/Pion
                - eventHists/nPFOsVsCosTheta/NeutralHadron
                - eventHists/nPFOsVsCosTheta/Muon
                - eventHists/nPFOsVsCosTheta/all
        legPos:
                - 0.35
                - 0.7
                - 0.65
                - 0.9
        yAxisRange:
                - 0.0
                - 1.5
        rebinFactor: 4
        scaleFactor: 0.25
        drawOption: HIST
        yAxisLabel: nPFOs
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0

# nPFOs_vs_theta_electron_E10_Brem:
#         dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/e-/codeTest_jan16/
#         fileName:
#                 - particleGun_E10.root
#         legTitle:
#                 - "Electron (Brem)"
#                 - "Photon"
#                 - "Pion"
#                 - "NeutralHadron"
#                 - "Muon"
#                 - "All"
#         histName:
#                 - eventHists_FSR/nPFOsVsCosTheta/Electron
#                 - eventHists_FSR/nPFOsVsCosTheta/Photon
#                 - eventHists_FSR/nPFOsVsCosTheta/Pion
#                 - eventHists_FSR/nPFOsVsCosTheta/NeutralHadron
#                 - eventHists_FSR/nPFOsVsCosTheta/Muon
#                 - eventHists_FSR/nPFOsVsCosTheta/all
#         legPos:
#                 - 0.35
#                 - 0.5
#                 - 0.65
#                 - 0.7
#         yAxisRange:
#                 - 0.0
#                 - 2.5
#         rebinFactor: 4
#         scaleFactor: 0.25
#         drawOptions: H
#         yAxisLabel: nPFOs
#         markerStyle:
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
# efficiency_vs_theta_electron_E10:
#         dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/e-/codeTest_jan16/
#         fileName:
#                 - particleGun_E10.root
#         legTitle:
#                 - "efficiency (electrons, E=10 GeV)"
#                 - "fail type"
#                 - "fail angular matching"
#                 - "fail energy mathing"
#                 - "sum (validation)"
#         histName:
#                 - eventHists/efficiencyVsCosTheta
#                 - eventHists/efficiencyVsCosThetaFailType
#                 - eventHists/efficiencyVsCosThetaFailAngularMatching
#                 - eventHists/efficiencyVsCosThetaFailEnergyMatching
#                 - eventHists/efficiencyVsCosThetaSum
#         legPos:
#                 - 0.3
#                 - 0.3
#                 - 0.8
#                 - 0.5
#         yAxisRange:
#                 - 0.0
#                 - 1.3
#         rebinFactor: 4
#         scaleFactor: 0.25
#         drawOptions: H
#         yAxisLabel: Efficiency
#         markerStyle:
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
# efficiency_vs_theta_electron_E10_noBrem:
#         dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/e-/codeTest_jan16/
#         fileName:
#                 - particleGun_E10.root
#         legTitle:
#                 - "efficiency (electrons, E=10 GeV, no Bream)"
#                 - "fail type"
#                 - "fail angular matching"
#                 - "fail energy mathing"
#                 - "sum (validation)"
#         histName:
#                 - eventHists_noFSR/efficiencyVsCosTheta
#                 - eventHists_noFSR/efficiencyVsCosThetaFailType
#                 - eventHists_noFSR/efficiencyVsCosThetaFailAngularMatching
#                 - eventHists_noFSR/efficiencyVsCosThetaFailEnergyMatching
#                 - eventHists_noFSR/efficiencyVsCosThetaSum
#         legPos:
#                 - 0.3
#                 - 0.3
#                 - 0.8
#                 - 0.5
#         yAxisRange:
#                 - 0.0
#                 - 1.3
#         rebinFactor: 4
#         scaleFactor: 0.25
#         drawOptions: H
#         yAxisLabel: Efficiency
#         markerStyle:
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
# efficiency_vs_theta_electron_E10_Brem:
#         dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/e-/codeTest_jan16/
#         fileName:
#                 - particleGun_E10.root
#         legTitle:
#                 - "efficiency (electrons, E=10 GeV, Bream)"
#                 - "fail type"
#                 - "fail angular matching"
#                 - "fail energy mathing"
#                 - "sum (validation)"
#         histName:
#                 - eventHists_FSR/efficiencyVsCosTheta
#                 - eventHists_FSR/efficiencyVsCosThetaFailType
#                 - eventHists_FSR/efficiencyVsCosThetaFailAngularMatching
#                 - eventHists_FSR/efficiencyVsCosThetaFailEnergyMatching
#                 - eventHists_FSR/efficiencyVsCosThetaSum
#         legPos:
#                 - 0.3
#                 - 0.3
#                 - 0.8
#                 - 0.5
#         yAxisRange:
#                 - 0.0
#                 - 1.3
#         rebinFactor: 4
#         scaleFactor: 0.25
#         drawOptions: H
#         yAxisLabel: Efficiency
#         markerStyle:
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#
# efficiency_vs_theta_electron_E100:
#         dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/e-/codeTest_jan16/
#         fileName:
#                 - particleGun_E100.root
#         legTitle:
#                 - "efficiency (electrons, E=100 GeV)"
#                 - "fail type"
#                 - "fail angular matching"
#                 - "fail energy mathing"
#                 - "sum (validation)"
#         histName:
#                 - eventHists/efficiencyVsCosTheta
#                 - eventHists/efficiencyVsCosThetaFailType
#                 - eventHists/efficiencyVsCosThetaFailAngularMatching
#                 - eventHists/efficiencyVsCosThetaFailEnergyMatching
#                 - eventHists/efficiencyVsCosThetaSum
#         legPos:
#                 - 0.3
#                 - 0.35
#                 - 0.8
#                 - 0.55
#         yAxisRange:
#                 - 0.0
#                 - 1.3
#         rebinFactor: 4
#         scaleFactor: 0.25
#         drawOptions: H
#         yAxisLabel: Efficiency
#         markerStyle:
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
# nPFOs_vs_theta_electron_E10_failType:
#         dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/e-/codeTest_jan16/
#         fileName:
#                 - particleGun_E10.root
#         legTitle:
#                 - "Electron (no electron PFO)"
#                 - "Photon"
#                 - "Pion"
#                 - "NeutralHadron"
#                 - "Muon"
#                 - "All"
#         histName:
#                 - eventHists/nPFOsVsCosThetaFailType/Electron
#                 - eventHists/nPFOsVsCosThetaFailType/Photon
#                 - eventHists/nPFOsVsCosThetaFailType/Pion
#                 - eventHists/nPFOsVsCosThetaFailType/NeutralHadron
#                 - eventHists/nPFOsVsCosThetaFailType/Muon
#                 # - eventHists_noFSR/nPFOsVsCosTheta/all
#         legPos:
#                 - 0.35
#                 - 0.5
#                 - 0.65
#                 - 0.7
#         yAxisRange:
#                 - 0.0
#                 - 2.5
#         rebinFactor: 4
#         scaleFactor: 0.25
#         drawOptions: H
#         yAxisLabel: nPFOs
#         markerStyle:
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#                 - 0
#
