default:
        yAxisTitleOffset: 0.95
        # skipMissingHists: 1
        savePictDir: singlPartAngularRes_sep
        # yAxisLabel: "Counts"
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/TEMPLATES/
        # legCaptionMode: "RMS"
        # normalize: True
        # logY: True
        # drawOption: "HIST"
        # xAxisRange:
        #     - -5
        #     - 5
        yAxisLabel: "Angular resolution [#circ]"
        legPos:
                - 0.2
                - 0.7
                - 0.78
                - 0.9

angularRes_kaon_vsCosTheta_0_1T:
        legTitle:
                # - "K0 #Delta#theta, 4 Tesla, 91.2 GeV"
                # - "K0 #Delta#phi, 4 Tesla, 91.2 GeV"
                # - "K0 #Delta#theta, 2 Tesla, 91.2 GeV"
                # - "K0 #Delta#phi, 2 Tesla, 91.2 GeV"
                - "K0 #Delta#theta, 0.1 Tesla, 91.2 GeV"
                - "K0 #Delta#phi, 0.1 Tesla, 91.2 GeV"
        fileName:
                # - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_4Tesla_truthTr_run1_files/DR11_hists.root
                # - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_2Tesla_truthTr_run1_files/DR11_hists.root
                - FCCee_o1_v03_ILCSoft-2018-10-11_gcc62_zuds_E91.2_TruthTr_0_1Tesla_truthTr_run1_files/DR11_hists.root
        histName: 
                - jetClustering/kaonThetaRes
                - jetClustering/kaonPhiRes
        yAxisRange:
                - 0.0
                - 2.0

angularRes_pion_vsCosTheta_0_1T:
        legTitle:
                # - "pi- #Delta#theta, 4 Tesla, 91.2 GeV"
                # - "pi- #Delta#phi, 4 Tesla, 91.2 GeV"
                # - "pi- #Delta#theta, 2 Tesla, 91.2 GeV"
                # - "pi- #Delta#phi, 2 Tesla, 91.2 GeV"
                - "pi- #Delta#theta, 0.1 Tesla, 91.2 GeV"
                - "pi- #Delta#phi, 0.1 Tesla, 91.2 GeV"
        fileName:
                # - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_4Tesla_truthTr_run1_files/DR11_hists.root
                # - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_2Tesla_truthTr_run1_files/DR11_hists.root
                - FCCee_o1_v03_ILCSoft-2018-10-11_gcc62_zuds_E91.2_TruthTr_0_1Tesla_truthTr_run1_files/DR11_hists.root
        histName: 
                - jetClustering/pionThetaRes
                - jetClustering/pionPhiRes
        yAxisRange:
                - 0.0
                - 0.1

angularRes_kaon_vsCosTheta_2T:
        legTitle:
                # - "K0 #Delta#theta, 4 Tesla, 91.2 GeV"
                # - "K0 #Delta#phi, 4 Tesla, 91.2 GeV"
                - "K0 #Delta#theta, 2 Tesla, 91.2 GeV"
                - "K0 #Delta#phi, 2 Tesla, 91.2 GeV"
                # - "K0 #Delta#theta, 0.1 Tesla, 91.2 GeV"
                # - "K0 #Delta#phi, 0.1 Tesla, 91.2 GeV"
        fileName:
                # - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_4Tesla_truthTr_run1_files/DR11_hists.root
                - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_2Tesla_truthTr_run1_files/DR11_hists.root
                # - FCCee_o1_v03_ILCSoft-2018-10-11_gcc62_zuds_E91.2_TruthTr_0_1Tesla_truthTr_run1_files/DR11_hists.root
        histName: 
                - jetClustering/kaonThetaRes
                - jetClustering/kaonPhiRes
        yAxisRange:
                - 0.0
                - 2.0

angularRes_pion_vsCosTheta_2T:
        legTitle:
                # - "pi- #Delta#theta, 4 Tesla, 91.2 GeV"
                # - "pi- #Delta#phi, 4 Tesla, 91.2 GeV"
                - "pi- #Delta#theta, 2 Tesla, 91.2 GeV"
                - "pi- #Delta#phi, 2 Tesla, 91.2 GeV"
                # - "pi- #Delta#theta, 0.1 Tesla, 91.2 GeV"
                # - "pi- #Delta#phi, 0.1 Tesla, 91.2 GeV"
        fileName:
                # - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_4Tesla_truthTr_run1_files/DR11_hists.root
                - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_2Tesla_truthTr_run1_files/DR11_hists.root
                # - FCCee_o1_v03_ILCSoft-2018-10-11_gcc62_zuds_E91.2_TruthTr_0_1Tesla_truthTr_run1_files/DR11_hists.root
        histName: 
                - jetClustering/pionThetaRes
                - jetClustering/pionPhiRes
        yAxisRange:
                - 0.0
                - 0.1

angularRes_kaon_vsCosTheta_4T:
        legTitle:
                - "K0 #Delta#theta, 4 Tesla, 91.2 GeV"
                - "K0 #Delta#phi, 4 Tesla, 91.2 GeV"
                # - "K0 #Delta#theta, 2 Tesla, 91.2 GeV"
                # - "K0 #Delta#phi, 2 Tesla, 91.2 GeV"
                # - "K0 #Delta#theta, 0.1 Tesla, 91.2 GeV"
                # - "K0 #Delta#phi, 0.1 Tesla, 91.2 GeV"
        fileName:
                - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_4Tesla_truthTr_run1_files/DR11_hists.root
                # - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_2Tesla_truthTr_run1_files/DR11_hists.root
                # - FCCee_o1_v03_ILCSoft-2018-10-11_gcc62_zuds_E91.2_TruthTr_0_1Tesla_truthTr_run1_files/DR11_hists.root
        histName: 
                - jetClustering/kaonThetaRes
                - jetClustering/kaonPhiRes
        yAxisRange:
                - 0.0
                - 2.0

angularRes_pion_vsCosTheta_4T:
        legTitle:
                - "pi- #Delta#theta, 4 Tesla, 91.2 GeV"
                - "pi- #Delta#phi, 4 Tesla, 91.2 GeV"
                # - "pi- #Delta#theta, 2 Tesla, 91.2 GeV"
                # - "pi- #Delta#phi, 2 Tesla, 91.2 GeV"
                # - "pi- #Delta#theta, 0.1 Tesla, 91.2 GeV"
                # - "pi- #Delta#phi, 0.1 Tesla, 91.2 GeV"
        fileName:
                - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_4Tesla_truthTr_run1_files/DR11_hists.root
                # - FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_TruthTr_2Tesla_truthTr_run1_files/DR11_hists.root
                # - FCCee_o1_v03_ILCSoft-2018-10-11_gcc62_zuds_E91.2_TruthTr_0_1Tesla_truthTr_run1_files/DR11_hists.root
        histName: 
                - jetClustering/pionThetaRes
                - jetClustering/pionPhiRes
        yAxisRange:
                - 0.0
                - 0.1

