photon_100GeV_noConv:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/gamma/FCCee_testConvertionDetection/
        fileName:
                - particleGun_E100_Theta45_46.root
        legTitle:
                - 1 photon PFO in event
                - ">2 PFOs, photon pass energy cut"
                - ">2 PFOs, photon doesn't pass cut"
        histName: 
                - PandoraPFOs_22/noConv_PFOofType_noAdditionalPFOs/Energy
                - PandoraPFOs_22/noConv_PFOofType_thereAreAdditionalPFOs_withinEnergyCut/Energy
                - PandoraPFOs_22/noConv_PFOofType_thereAreAdditionalPFOs_outsideEnergyCut/Energy
        legPos:
                - 0.12
                - 0.7
                - 0.68
                - 0.9
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        xAxisRange:
                - 0
                - 120
        yAxisRange:
                - 0.1
                - 100
        histTitle: "Most En. Photon PFO, FCC-ee,  E_{#gamma}=100 GeV, no photon convertion"
        legCaptionMode: entries
        # logY: 1
photon_100GeV_conv:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/gamma/FCCee_testConvertionDetection/
        fileName:
                - particleGun_E100.root
        legTitle:
                - 1 photon PFO in event
                - ">2 PFOs, photon pass energy cut"
                - ">2 PFOs, photon doesn't pass cut"
        histName: 
                - PandoraPFOs_22/conv_PFOofType_noAdditionalPFOs/Energy
                - PandoraPFOs_22/conv_PFOofType_thereAreAdditionalPFOs_withinEnergyCut/Energy
                - PandoraPFOs_22/conv_PFOofType_thereAreAdditionalPFOs_outsideEnergyCut/Energy
        legPos:
                - 0.12
                - 0.7
                - 0.68
                - 0.9
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        xAxisRange:
                - 0
                - 120
        yAxisRange:
                - 0.1
                - 100
        histTitle: "Most En. Photon PFO, FCC-ee, E_{#gamma}=100 GeV, photon convertion"
        legCaptionMode: entries
        # logY: 1
photon_100GeV_crack:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/gamma/FCCee_testConvertionDetection/
        fileName:
                - particleGun_E100.root
        legTitle:
                - 1 photon PFO in event
                - ">2 PFOs, photon pass energy cut"
                - ">2 PFOs, photon doesn't pass cut"
        histName: 
                - PandoraPFOs_22/noConv_PFOofType_noAdditionalPFOs/Energy
                - PandoraPFOs_22/noConv_PFOofType_thereAreAdditionalPFOs_withinEnergyCut/Energy
                - PandoraPFOs_22/noConv_PFOofType_thereAreAdditionalPFOs_outsideEnergyCut/Energy
        legPos:
                - 0.12
                - 0.7
                - 0.68
                - 0.9
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        xAxisRange:
                - 0
                - 120
        yAxisRange:
                - 0.1
                - 100
        histTitle: "Most En. Photon PFO, FCC-ee,  E_{#gamma}=100 GeV, no photon convertion"
        legCaptionMode: entries
        # logY: 1
