photonRes_vs_energy:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/gamma/nominalEfficiency_nov1/out/ 
        fileName:
                - outFile.root 
        histName: 
                - energy_energyResolution
        yAxisRange:
                - 0
                - 8
        yAxisLabel: "#sigma(E_{photon})/E_{photon} [%]"

