default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/build_20jun2019/PhotonECAL/
        yAxisTitleOffset: 0.95
        savePictDir: "photonRes_21jun2019"
        legPos: [0.6, 0.65, 0.9, 0.9]
        # markerSize: 1.2
        markerSize: 1.5
        drawOption: AP
        sameDrawOption: P
        markerStyle:
                - 20
                - 21
        xAxisLabel: "Energy [GeV]"
        legTitle:
            - "40 layers"
            - "30 layers"
            - "20 layers"
            - "20+10 layers"
        histName: 
            - Graph
        yAxisLabel: "#sigma_{#gamma}/E_{#gamma} [%]"
        yAxisRange: [1.5, 10.0]
        # drawHistFuncs: True
        textLabel0:
            pos: [0.0, 1.02]
            title: "FCC-ee CLD"
            TextSize: 0.04

photonRes_barrel_ecal40_ecal30_ecal20_ecal20_10:
        fileName:
            - old/SinglePart_gamm/eventHists_noConv__Theta50_130_Photon.root
            - ecal30/eventHists_noConv__Theta50_130_Photon.root
            - ecal20/eventHists_noConv__Theta50_130_Photon.root
            - ecal20_10_fixed_v2_factor1_9/eventHists_noConv__Theta50_130_Photon.root

photonRes_endcap_ecal40_ecal30_ecal20_ecal20_10:
        fileName:
            - old/SinglePart_gamm/eventHists_noConv__Theta15_40_Photon.root
            - ecal30/eventHists_noConv__Theta15_40_Photon.root
            - ecal20/eventHists_noConv__Theta15_40_Photon.root
            - ecal20_10_fixed_v2_factor1_9/eventHists_noConv__Theta15_40_Photon.root
