photon_100GeV:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/build/PhotonECAL/FCCee_singleParticle_performace/gamma/nominalEfficiency_nov14/
        fileName:
                - particleGun_E100_Theta0_Phi0.root
        legTitle:
                # - neutral PFO
                - 1 photon PFO in event
                - ">2 PFOs, photon pass energy cut"
                - ">2 PFOs, photon doesn't pass cut"
                - no photon PFOs in event
        histName: 
                # - PandoraPFOs_2112/signalPFO_noAdditionalPFOs/Energy
                - PandoraPFOs_22/PFOofType_noAdditionalPFOs/Energy
                - PandoraPFOs_22/PFOofType_thereAreAdditionalPFOs_withinEnergyCut/Energy
                - PandoraPFOs_22/PFOofType_thereAreAdditionalPFOs_outsideEnergyCut/Energy
                - PandoraPFOs_22/mostEnergeticPFO_noPFOofType/Energy
        legPos:
                - 0.12
                - 0.7
                - 0.68
                - 0.9
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        xAxisRange:
                - 0
                - 110
        yAxisRange:
                - 0.1
                - 300
        histTitle: "Photon gun, E: 100 GeV, uniform cos(theta)"
        legCaptionMode: entries
        # logY: 1
