photon_10GeV:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/build/PhotonECAL/FCCee_singleParticle_performace/gamma/nominalEfficiency_nov14/
        fileName:
                - particleGun_E10_Theta0_Phi0.root
        legTitle:
                # - neutral PFO
                - one photon PFO
                - pass energy cut
                - don't pass energy cut
                - no photon PFOs reconstructed
        histName: 
                # - PandoraPFOs_2112/signalPFO_noAdditionalPFOs/Energy
                - PandoraPFOs_22/PFOofType_noAdditionalPFOs/Energy
                - PandoraPFOs_22/PFOofType_thereAreAdditionalPFOs_withinEnergyCut/Energy
                - PandoraPFOs_22/PFOofType_thereAreAdditionalPFOs_outsideEnergyCut/Energy
                - PandoraPFOs_22/mostEnergeticPFO_noPFOofType/Energy
        legPos:
                - 0.12
                - 0.7
                - 0.68
                - 0.9
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        xAxisRange:
                - 0
                - 13
        yAxisRange:
                - 0.1
                - 1000
        histTitle: "Photon gun, E: 10 GeV, uniform cos(theta)"
        legCaptionMode: entries
        # logY: 1
