pion_eff:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/pi-_noAngNoMomMatching/
        fileName:
                - particleGun_E2_Theta9_171.root
                - particleGun_E5_Theta9_171.root
                - particleGun_E10_Theta9_171.root
        legTitle:
                - 2 GeV
                - 5 GeV
                - 10 GeV
        histName: 
                - eventHists/PFOType
        legPos:
                - 0.12
                - 0.6
                - 0.68
                - 0.8
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        # xAxisRange:
        #         - 0
        #         - 5.5
        # yAxisRange:
        #         - 0.5
        #         - 1.0
        histTitle: "E_{e}=100 GeV"
        # legCaptionMode: entries
        logY: 1
        # rebinFactor: 5
        # scaleFactor: 0.2
        drawOption: HIST
        yAxisLabel: Efficiency
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0
