pion_eff:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/pi-/
        fileName:
                - newAngularRequirements/particleGun_E5_Theta9_171.root
                - oldAngularRequirements/particleGun_E5_Theta9_171.root
                # - particleGun_E10_Theta9_171.root
                # - particleGun_E20_Theta9_171.root
                # - particleGun_E100_Theta9_171.root
        legTitle:
                - "new"
                - "old"
                # - "nominal efficiency"
                # - "convertion events included"
                # - "convertion events excluded"
                # - "convertion events required"
                # - "photon reclustering 0.2 rad (11.5 deg)"
                # - "photon+neutral reclustering"
                # - "photon+neutral reclustering (looser theta cut)"
                # - "mom-dep photon reclustering (11.5 + 60/p deg)"
        histName: 
                - eventHists/efficiencyVsCosTheta
                # - eventHists/efficiencyVsCosThetaFailAngularMatching
                # - eventHists_noConv/efficiencyVsCosTheta
                # - eventHists_conv/efficiencyVsCosTheta
                # - eventHists_photonRecl/efficiencyVsCosTheta
                # - eventHists_photonAndNeutralRecl/efficiencyVsCosTheta
                # - eventHists_photonAndNeutralRecl_looseThetaCut/efficiencyVsCosTheta
                # - eventHists_noFSR/efficiencyVsCosTheta
                # - eventHists_photonMerge/efficiencyVsCosTheta
                # - eventHists_photonAndNeutralLooseMerge/efficiencyVsCosTheta
                # - eventHists_photonReclMomDep/efficiencyVsCosTheta
        legPos:
                - 0.12
                - 0.2
                - 0.68
                - 0.4
        # xAxisRange:
        #         - 0
        #         - 120
        yAxisRange:
                - 0.5
                - 1.0
        histTitle: "E_{e}=100 GeV"
        # legCaptionMode: entries
        # logY: 1
        rebinFactor: 4
        scaleFactor: 0.25
        drawOption: HIST
        yAxisLabel: Efficiency
        markerStyle:
                - 0
                - 0
                - 0
                - 0
                - 0
