pion_eff_vs_energy_comp:
        # drawOption: ALP
        # sameDrawOption: LP
        sortXaxisInGraph: True
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/FCCee_o1_v02/ 
        fileName:
                # - eventHists_noConv.root
                - pi-_rerun/eventHists.root
                - pi-_noAngNoMomMatching/eventHists.root
                # - eventHists_photonRecl.root
                # - eventHists_photonAndNeutralRecl.root
                # - eventHists_photonAndNeutralRecl_looseThetaCut.root
        legTitle:
                # - no photon convertion events
                # - nominal efficiency
                # - photon PFO reclustering
                # - photon+neutral reclustering
                # - photon+neutral PFO reclustering (looser cut)
                # - photon+neutral PFO reclustering
                - pion efficiency
                - no ang&mom matching
        histName: 
                - Graph 
        legPos:
                - 0.2
                - 0.2
                - 0.7
                - 0.3
        lineWidth: 1
        canPos:
                - 0
                - 0
                - 800
                - 800
        yAxisLabel: "Efficiency"
        xAxisLabel: "Energy [GeV]"
        # gridX: 1
        # gridY: 1
        yAxisRange:
                - 0.8
                - 1.0
        markerSize: 1.2
        drawOption: AP
        sameDrawOption: P
        markerStyle:
                - 20
                - 21
                - 22
                - 33
                - 34
                # - 0
                # - 0
                # - 0
                # - 0
                # - 0
