default:
        legPos:
                - 0.2
                - 0.7
                - 0.78
                - 0.9
        yAxisRange:
                - 0.75
                - 8
        yAxisTitleOffset: 0.95
        # skipMissingHists: 1
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/TEMPLATES/FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E365_ConformalTr_defaultSetting_jun26_files/
        histName: 
                - jetClustering/2SCrystalBallSigmaResVsCosTheta
                - jetClustering/ResVsCosTheta
                - jetClustering/2SCrystalBall_LeftLimit_VsCosThetaHist
                # - jetClustering/2SCrystalBall_RightLimit_VsCosThetaHist
                - jetClustering/2SCrystalBall_GaussCoreWidth_VsCosThetaHist
        savePictDir: jetClusteringFitVsBinning_DR11/
        yAxisLabel: "Resolution [%]"

JER_365_RMS90_90bins:
        legTitle:
                - "90 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR11_90bins.root

JER_365_RMS90_105bins:
        legTitle:
                - "105 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR11_105bins.root

JER_365_RMS90_120bins:
        legTitle:
                - "120 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR11_120bins.root

JER_365_RMS90_135bins:
        legTitle:
                - "135 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR11_135bins.root

JER_365_RMS90_150bins:
        legTitle:
                - "150 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR11_150bins.root

JER_365_RMS90_165bins:
        legTitle:
                - "165 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR11_165bins.root

JER_365_RMS90_180bins:
        legTitle:
                - "180 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR11_180bins.root

JER_365_RMS90_195bins:
        legTitle:
                - "195 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR11_195bins.root

JER_365_RMS90_210bins:
        legTitle:
                - "210 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR11_210bins.root

JER_365_RMS90_150bins_final:
        legTitle:
                - "RMS_{90}(E_{j})/Mean_{90}(E_{j})"
                - "#sigma_{fit}(E_{j})/Mean_{fit}(E_{j})"
                # - "a1"
                # - "a2"
                # - "(a1+a2)/2"
        fileName:
                - DR11_150bins.root
        histName: 
                - jetClustering/ResVsCosTheta
                - jetClustering/2SCrystalBallSigmaResVsCosTheta
                # - totalEnergy/2SCrystalBall_LeftLimit_VsCosThetaHist
                # - totalEnergy/2SCrystalBall_RightLimit_VsCosThetaHist
                # - totalEnergy/2SCrystalBall_GaussCoreWidth_VsCosThetaHist
