default:
        legPos:
                - 0.2
                - 0.7
                - 0.78
                - 0.9
        yAxisRange:
                - 0.75
                - 8
        yAxisTitleOffset: 0.95
        # skipMissingHists: 1
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/TEMPLATES/FCCee_o1_v03_ILCSoft-2018-08-10_gcc62_zuds_E91.2_ConformalTr_defaultSetting_jun26_files/
        histName: 
                - jetClustering/2SCrystalBallSigmaResVsCosTheta
                - jetClustering/ResVsCosTheta
                - jetClustering/2SCrystalBall_LeftLimit_VsCosThetaHist
                # - jetClustering/2SCrystalBall_RightLimit_VsCosThetaHist
                - jetClustering/2SCrystalBall_GaussCoreWidth_VsCosThetaHist
        savePictDir: jetClusteringFitVsBinning_DR07/
        histNamePrefix: JER_91_2_RMS90_vs_Fit_

90bins:
        legTitle:
                - "90 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR07_90bins.root

105bins:
        legTitle:
                - "105 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR07_105bins.root

120bins:
        legTitle:
                - "120 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR07_120bins.root

135bins:
        legTitle:
                - "135 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR07_135bins.root

150bins:
        legTitle:
                - "150 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR07_150bins.root

165bins:
        legTitle:
                - "165 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR07_165bins.root

180bins:
        legTitle:
                - "180 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR07_180bins.root

195bins:
        legTitle:
                - "195 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR07_195bins.root

210bins:
        legTitle:
                - "210 bins"
                - "RMS90"
                # - "a1"
                - "a2"
                - "(a1+a2)/2"
        fileName:
                - DR07_210bins.root
