testing_eff_vs_theta:
        # dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/gamma/FCCee_testConvertionDetection/fullTheta2/
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/gamma/
        # dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/gamma/codeTest_jan11/
        fileName:
                - codeTest_jan11/particleGun_E100.root
                # - particleGun_E100.root
                - FCCee_testConvertionDetection/fullTheta2/particleGun_E100.root
        legTitle:
                - "new"
                - "old"
                # - "convertion events included"
                # - "convertion events excluded"
                # - "convertion events required"
                # - "photon reclustering"
                # - "photon+neutral reclustering"
                # - "photon+neutral reclustering (looser theta cut)"
        histName: 
                # - eventHists/efficiencyVsCosTheta
                # - eventHists_noConv/efficiencyVsCosTheta
                # - eventHists_conv/efficiencyVsCosTheta
                # - eventHists_photonRecl/efficiencyVsCosTheta
                # - eventHists_photonAndNeutralRecl/efficiencyVsCosTheta
                - eventHists_photonAndNeutralRecl_looseThetaCut/efficiencyVsCosTheta
                # - eventHists_noFSR/efficiencyVsCosTheta
                # - eventHists_photonMerge/efficiencyVsCosTheta
                # - eventHists_photonAndNeutralLooseMerge/efficiencyVsCosTheta
        legPos:
                - 0.12
                - 0.7
                - 0.68
                - 0.9
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        # xAxisRange:
        #         - 0
        #         - 120
        yAxisRange:
                - 0.0
                - 1.5
        histTitle: "E_{#gamma}=100 GeV"
        # legCaptionMode: entries
        # logY: 1
        rebinFactor: 4
        scaleFactor: 0.25
        drawOption: ""
        # sameDrawOption: "E1"
        yAxisLabel: Efficiency
