default:
        legTitle:
                - "layer 00"
                - "layer 30"
                - "layer 40"
                - "layer 50"
                - "layer 80"
                - "layer 90"
        dirPrefix: /afs/cern.ch/work/o/oviazlo/HGCAL_DPG/
        # markerStyle:
        #         - 0
        #         - 0
        #         - 0
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/fake_eta_layer00"
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/fake_eta_layer30"
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/fake_eta_layer40"
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/fake_eta_layer50"
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/fake_eta_layer80"
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/fake_eta_layer90"
        legPos:
                - 0.45
                - 0.65
                - 0.65
                - 0.9
        yAxisRange:
                - 0
                - 1.05
        xAxisRange:
                - -3.0
                - 3.0
        yAxisLabel: "Cluster Layer Fake Rate"
        xAxisLabel: "#eta"



layerFakeRate_MIP_TICL_kappa_9_ecut3:
        fileName:
            - CMSSW_11_1_X_2020-02-17-2300/src/23289.0_SingleMuPt15Eta1p7_2p7+SingleMuPt15Eta1p7_2p7_2026D49_GenSimHLBeamSpotFull+DigiFullTrigger_2026D49+RecoFullGlobal_2026D49+HARVESTFullGlobal_2026D49/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
        textLabel0:
            pos:
                - 0.3
                - 0.4
            title: "Kappa: 9; Ecut: 3"

layerFakeRate_MIP_TICL_kappa_5_ecut2:
        fileName:
            - modPackage_MIPchange_kappa_5_ecut2/CMSSW_11_1_X_2020-02-17-2300/src/23289.0/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
        textLabel0:
            pos:
                - 0.3
                - 0.4
            title: "Kappa: 5; Ecut: 2"


layerFakeRate_MIP_TICL_kappa_5_ecut3:
        fileName:
            - modPackage_MIPchange_kappa_5/CMSSW_11_1_X_2020-02-17-2300/src/23289.0/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
        textLabel0:
            pos:
                - 0.3
                - 0.4
            title: "Kappa: 5; Ecut: 3"

layerFakeRate_MIP_TICL_kappa_3_ecut3:
        fileName:
            - modPackage_MIPchange/CMSSW_11_1_X_2020-02-17-2300/src/23289.0/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
        textLabel0:
            pos:
                - 0.3
                - 0.4
            title: "Kappa: 3; Ecut: 3"
