default:
        silentMode: True
        # legTitle:
        #         - "nMissingLayers = 0"
        #         - "nMissingLayers = 1"
        dirPrefix: /afs/cern.ch/work/o/oviazlo/HGCAL_DPG/
        # markerStyle:
        #         - 0
        #         - 0
        #         - 0
        histName:
                - "h_z"
        # legPos:
        #         - 0.45
        #         - 0.25
        #         - 0.65
        #         - 0.4
        yAxisRange:
                - 0
                - 300
        xAxisRange:
                - 329
                - 380
        yAxisLabel: "Entries"
        xAxisLabel: "z coordinate of hits [cm]"
        savePictDir: "debugCellularAutomaton"


zDistr_cosTheta_0_94:
        fileName:
            - kappa_5_nMissingLayers_0/CMSSW_11_1_0_pre6/src/23289.0_SingleMuPt15Eta1p7_2p7+SingleMuPt15Eta1p7_2p7_2026D49_GenSimHLBeamSpotFull+DigiFullTrigger_2026D49+RecoFullGlobal_2026D49+HARVESTFullGlobal_2026D49/logs_defaultCosTheta/nMissingLayers1/hists.root

