default:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/LCPandoraAnalysis/RUN/ 
        fileName:
                - nominal_trackClusterDistance/hist_Zuds91.root
                - 20mm_trackClusterDistance/hist_Zuds91.root
                - 50mm_trackClusterDistance/hist_Zuds91.root
                # - oldRootFiles/hist_Zuds91.root
        legTitle:
                - "Nominal cut (3mm, 10mm)"
                - "Mod cut (20mm, 20mm)"
                - "Mod cut (50mm, 50mm)"
                # - "OLD RESULTS (cross check)"
        markerStyle:
                - 0
                - 0
                - 0


TrackClusterDistanceCut_totalEnergy_Zuds91:
        histName: 
                - fPFA_L6A 
        drawOption: HIST
        legPos:
                - 0.2
                - 0.7
                - 0.65
                - 0.9
        legCaptionMode: mean
        xAxisRange:
                # - 200
                # - 450
                - 0
                - 120
        rebinFactor: 20
        # scaleFactor: 0.1

TrackClusterDistanceCut_resolutionVsCosTheta_Zuds91:
        histName:
                - ResVsCosTheta
        legPos:
                - 0.2
                - 0.7
                - 0.65
                - 0.9
        yAxisRange:
                - 0
                - 10

