default:
        silentMode: True
        xAxisTitleSize: 0.05
        xAxisTitleOffset: 1.3
        dirPrefix: /afs/cern.ch/work/o/oviazlo/HGCAL_DPG/
        savePictDir: "pre7_layerEff_noNoise"
        legTitle:
                - "layer 00"
                - "layer 10"
                - "layer 27"
                - "layer 28"
                - "layer 30"
                - "layer 45"
        legPos:
                - 0.45
                - 0.6
                - 0.65
                - 0.9
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/totclusternum_layer_00"
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/totclusternum_layer_10"
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/totclusternum_layer_27"
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/totclusternum_layer_28"
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/totclusternum_layer_30"
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/hgcalLayerClusters/totclusternum_layer_45"
        xAxisLabel: "Number of clusters per layer"
        yAxisLabel: "Entries"
        yAxisRange:
                - 0
                - 1000
        xAxisRange:
                - 0
                - 20

nLayerClusters_kappa_5_cosTheta_0_97_noNoise:
        fileName:
            - pre7_kappa_5_minCosTheta_0_97_noNoise/CMSSW_11_1_0_pre7/src/23289.0_SingleMuPt15Eta1p7_2p7+SingleMuPt15Eta1p7_2p7_2026D49_GenSimHLBeamSpotFull+DigiFullTrigger_2026D49+RecoFullGlobal_2026D49+HARVESTFullGlobal_2026D49/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
        
nLayerClusters_kappa_5_noNoise:
        fileName:
            - pre7_kappa_5_noNoise/CMSSW_11_1_0_pre7/src/23289.0_SingleMuPt15Eta1p7_2p7+SingleMuPt15Eta1p7_2p7_2026D49_GenSimHLBeamSpotFull+DigiFullTrigger_2026D49+RecoFullGlobal_2026D49+HARVESTFullGlobal_2026D49/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root

nLayerClusters_kappa_5_cosTheta_0_97:
        fileName:
            - pre7_kappa_5_minCosTheta_0_97/CMSSW_11_1_0_pre7/src/23289.0_SingleMuPt15Eta1p7_2p7+SingleMuPt15Eta1p7_2p7_2026D49_GenSimHLBeamSpotFull+DigiFullTrigger_2026D49+RecoFullGlobal_2026D49+HARVESTFullGlobal_2026D49/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
        
nLayerClusters_kappa_5:
        fileName:
            - pre7_kappa_5/CMSSW_11_1_0_pre7/src/23289.0_SingleMuPt15Eta1p7_2p7+SingleMuPt15Eta1p7_2p7_2026D49_GenSimHLBeamSpotFull+DigiFullTrigger_2026D49+RecoFullGlobal_2026D49+HARVESTFullGlobal_2026D49/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
