default:
        silentMode: True
        savePictDir: "pre7_multicluster_MIP_noNoise_nCells_3"
        xAxisTitleSize: 0.04
        xAxisTitleOffset: 1.3
        legTitle:
                # - "with noise"
                - "no noise, maxNCells=2"
                - "no noise, maxNCells=3"
        dirPrefix: /afs/cern.ch/work/o/oviazlo/HGCAL_DPG/
        legPos:
                - 0.45
                - 0.75
                - 0.75
                - 0.9
        # yAxisRange:
        #         - 0
        #         - 1000
        # xAxisRange:
        #         - 0.0
        #         - 0.5
        # yAxisLabel: "Entries"
        # xAxisLabel: "Clustered energy in layer [GeV?]"
        fileName:
            # - pre7_kappa_5/CMSSW_11_1_0_pre7/src/23289.0_SingleMuPt15Eta1p7_2p7+SingleMuPt15Eta1p7_2p7_2026D49_GenSimHLBeamSpotFull+DigiFullTrigger_2026D49+RecoFullGlobal_2026D49+HARVESTFullGlobal_2026D49/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
            - pre7_kappa_5_noNoise/CMSSW_11_1_0_pre7/src/23289.0_SingleMuPt15Eta1p7_2p7+SingleMuPt15Eta1p7_2p7_2026D49_GenSimHLBeamSpotFull+DigiFullTrigger_2026D49+RecoFullGlobal_2026D49+HARVESTFullGlobal_2026D49/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
            - pre7_kappa_5_noNoise_nCells_3/CMSSW_11_1_0_pre7/src/23289.0_SingleMuPt15Eta1p7_2p7+SingleMuPt15Eta1p7_2p7_2026D49_GenSimHLBeamSpotFull+DigiFullTrigger_2026D49+RecoFullGlobal_2026D49+HARVESTFullGlobal_2026D49/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root

totmulticlusternum_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/totmulticlusternum"
        # yAxisLabel: 
        xAxisLabel: "total number of multiclusters"
        yAxisRange:
                - 0
                - 1050
        xAxisRange:
                - 0.0
                - 10.0

SharedEnergy_caloparticle2multicl_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/SharedEnergy_caloparticle2multicl"
        # yAxisLabel: 
        xAxisLabel: "Shared Energy of CaloParticle per Multi Cluster"
        yAxisRange:
                - 0.0
                - 300

Score_caloparticle2multicl_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/Score_caloparticle2multicl"
        # yAxisLabel: 
        xAxisLabel: "Score of CaloParticle per Multi Cluster"
        rebinFactor: 10
        xAxisRange:
                - 0.0
                - 1.0
        yAxisRange:
                - 0.0
                - 2005
                  
clusternum_in_multicluster_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/clusternum_in_multicluster"
        # yAxisLabel: 
        xAxisLabel: "total number of layer clusters in multicluster"
        xAxisRange:
                - 0.0
                - 100
        legPos:
                - 0.65
                - 0.75
                - 0.95
                - 0.9
        yAxisRange:
                - 0.0
                - 1400.0

effic_eta_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/effic_eta"
        yAxisLabel: "Efficiency"
        xAxisLabel: "#eta"
        yAxisRange:
                - 0.0
                - 1.05
        legPos:
                - 0.35
                - 0.2
                - 0.75
                - 0.35

effic_phi_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/effic_phi"
        yAxisLabel: "Efficiency"
        xAxisLabel: "#phi"
        yAxisRange:
                - 0.0
                - 1.05
        legPos:
                - 0.35
                - 0.2
                - 0.75
                - 0.35

fake_eta_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/fake_eta"
        yAxisLabel: "Fake Rate"
        xAxisLabel: "#eta"

multicluster_layersnum_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/multicluster_layersnum"
        xAxisLabel: "Number of layers of the multicluster"
        xAxisRange:
                - 0.0
                - 100
        legPos:
                - 0.65
                - 0.75
                - 0.95
                - 0.9
        yAxisRange:
                - 0.0
                - 700.0


Denom_CaloParticle_Eta_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/Denom_CaloParticle_Eta"
        yAxisLabel: "Denom CaloParticle"
        xAxisLabel: "#eta"
        yAxisRange:
                - 0.0
                - 120.0

Denom_MultiCluster_Eta_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/Denom_MultiCluster_Eta"
        yAxisLabel: "Denom MultiCluster"
        xAxisLabel: "#eta"
        yAxisRange:
                - 0.0
                - 120.0

Num_CaloParticle_Eta_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/Num_CaloParticle_Eta"
        yAxisLabel: "Num CaloParticle"
        xAxisLabel: "#eta"
        yAxisRange:
                - 0.0
                - 120.0

Num_MultiCluster_Eta_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/Num_MultiCluster_Eta"
        yAxisLabel: "Num MultiCluster"
        xAxisLabel: "#eta"
        yAxisRange:
                - 0.0
                - 120.0

Num_MultiCluster_Eta_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/Num_MultiCluster_Eta"
        yAxisLabel: "Num MultiCluster"
        xAxisLabel: "#eta"
        yAxisRange:
                - 0.0
                - 120.0

# _MIP_TICL_vs_kappa:
#         histName:
#                 - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/"

duplicate_eta_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/duplicate_eta"
        yAxisLabel: "Duplicate rate"
        xAxisLabel: "#eta"
        yAxisRange:
                - 0.0
                - 1.05

multicluster_lastlayer_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/multicluster_lastlayer"
        xAxisLabel: "Last layer of the multicluster"
        xAxisRange:
                - 0.0
                - 100
        legPos:
                - 0.65
                - 0.75
                - 0.95
                - 0.9
        yAxisRange:
                - 0.0
                - 700.0
                  
multicluster_firstlayer_MIP_TICL_vs_kappa:
        histName:
                - "DQMData/Run 1/HGCAL/Run summary/HGCalValidator/ticlMultiClustersFromTrackstersMIP/multicluster_firstlayer"
        xAxisLabel: "First layer of the multicluster"
        xAxisRange:
                - 0.0
                - 100
        legPos:
                - 0.65
                - 0.75
                - 0.95
                - 0.9
        yAxisRange:
                - 0.0
                - 700.0
